USE DATABASE HRMS;

USE SCHEMA TABLETYPE;

CREATE OR REPLACE TABLE LOCATIONS
(
    LOCATION_ID NUMBER(4),
    STREET_ADDRESS VARCHAR(40),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(25),
    COUNTRY_ID CHAR(2)
);    


SHOW TABLES LIKE 'LOCATIONS';

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1000 , '1297 VIA COLA DI RIE', '00989', 'ROMA', NULL, 'IT');
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1100, '93091 CALLE DELLA TESTA', '10934', 'VENICE', NULL, 'IT');
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1200, '2017 SHINJUKU-KU', '1689', 'TOKYO', 'TOKYO PREFECTURE', 'JP');
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1300, '9450 KAMIYA-CHO', '6823', 'HIROSHIMA', NULL, 'JP');
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1400, '2014 JABBERWOCKY RD', '26192', 'SOUTHLAKE', 'TEXAS', 'US');
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES ( 1500, '2011 INTERIORS BLVD', '99236', 'SOUTH SAN FRANCISCO', 'CALIFORNIA', 'US');
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1600, '2007 ZAGORA ST', '50090', 'SOUTH BRUNSWICK', 'NEW JERSEY', 'US');
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1700, '2004 CHARADE RD', '98199', 'SEATTLE', 'WASHINGTON', 'US');
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1800, '147 SPADINA AVE', 'M5V 2L7', 'TORONTO', 'ONTARIO', 'CA');
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1900, '6092 BOXWOOD ST', 'YSW 9T2', 'WHITEHORSE', 'YUKON', 'CA');



SELECT * FROM LOCATIONS;

CREATE  TABLE LOCATIONS
(
    LOCATION_ID NUMBER(4),
    STREET_ADDRESS VARCHAR(40),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(25),
    COUNTRY_ID CHAR(2)
);    


CREATE  TEMPORARY TABLE LOCATIONS
(
    LOCATION_ID NUMBER(4),
    STREET_ADDRESS VARCHAR(40),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(25),
    COUNTRY_ID CHAR(2)
);    

SHOW TABLES LIKE 'LOCATIONS';

SELECT * FROM LOCATIONS;

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES (1900, '6092 BOXWOOD ST', 'YSW 9T2', 'WHITEHORSE', 'YUKON', 'CA');

DROP TABLE LOCATIONS;

SHOW TABLES LIKE 'LOCATIONS';

SELECT * FROM LOCATIONS;