USE DATABASE HRMS; 


CREATE OR REPLACE  SCHEMA TABLETYPE;


CREATE OR REPLACE  TABLE LOCATIONS
(
    LOCATION_ID         NUMBER(4),
    STREET_ADDRESS      VARCHAR(40),
    POSTAL_CODE         VARCHAR(12),
    CITY                VARCHAR(30),
    STATE_PROVINCE      VARCHAR(25),
    COUNTRY_ID          CHAR(2)
);    


SHOW TABLES IN SCHEMA TABLETYPE;



SELECT *  FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA ='TABLETYPE';


ALTER TABLE LOCATIONS SET DATA_RETENTION_TIME_IN_DAYS=90;

SHOW TABLES LIKE 'LOCATIONS';


--TRANSIENT TABLE

CREATE OR REPLACE TRANSIENT TABLE LOCATIONS_TRANSIENT
(
    LOCATION_ID         NUMBER(4),
    STREET_ADDRESS      VARCHAR(40),
    POSTAL_CODE         VARCHAR(12),
    CITY                VARCHAR(30),
    STATE_PROVINCE      VARCHAR(25),
    COUNTRY_ID          CHAR(2)
);    

SHOW TABLES IN SCHEMA TABLETYPE;


SELECT *  FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA ='TABLETYPE';

ALTER TABLE LOCATIONS_TRANSIENT SET DATA_RETENTION_TIME_IN_DAYS=2;


SHOW TABLES LIKE 'LOCATIONS_TRANSIENT';


--TEMPORARY TABLES

CREATE OR REPLACE TEMPORARY TABLE LOCATIONS_TEMPORARY
(
    LOCATION_ID         NUMBER(4),
    STREET_ADDRESS      VARCHAR(40),
    POSTAL_CODE         VARCHAR(12),
    CITY                VARCHAR(30),
    STATE_PROVINCE      VARCHAR(25),
    COUNTRY_ID          CHAR(2)
);    

SHOW TABLES LIKE 'LOCATIONS_TEMPORARY';

SELECT *  FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA ='TABLETYPE';


ALTER TABLE LOCATIONS_TEMPORARY SET DATA_RETENTION_TIME_IN_DAYS=2;


--DATABASE PERMANENT, TRANSIENT AND TEMPORARY.

CREATE OR REPLACE  DATABASE HRMS_PERMANENT;

SHOW DATABASES LIKE 'HRMS_PERMANENT';

CREATE OR REPLACE TRANSIENT SCHEMA TYPE_TRANSIENT;

SHOW SCHEMAS LIKE 'TYPE_TRANSIENT'

CREATE OR REPLACE TABLE LOCATIONS_SCHEMA_TRANSIENT
(
    LOCATION_ID       NUMBER(4),
    STREET_ADDRESS    VARCHAR(40),
    POSTAL_CODE       VARCHAR(12),
    CITY              VARCHAR(30),
    STATE_PROVINCE    VARCHAR(25),
    COUNTRY_ID        CHAR(2)
);    

SHOW TABLES IN SCHEMA TYPE_TRANSIENT;

CREATE OR REPLACE TEMPORARY TABLE LOCATIONS_TEMPORARY
(
    LOCATION_ID         NUMBER(4),
    STREET_ADDRESS      VARCHAR(40),
    POSTAL_CODE         VARCHAR(12),
    CITY                VARCHAR(30),
    STATE_PROVINCE      VARCHAR(25),
    COUNTRY_ID          CHAR(2)
);    


SHOW TABLES IN SCHEMA TYPE_TRANSIENT;



CREATE OR REPLACE TRANSIENT DATABASE HRMS_TRANSIENT;


CREATE OR REPLACE SCHEMA TYPE_UNKNOWN

SHOW SCHEMAS

CREATE OR REPLACE TEMPORARY DATABASE  HRMS_TEMPORARY;

CREATE OR REPLACE TEMPORARY SCHEMA  TYPE_TEMPORARY;



CREATE_DDL_HRMS_HR.sql