CREATE OR REPLACE DATABASE HRMS;

CREATE OR REPLACE SCHEMA HR;

DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS LOCATIONS;
DROP TABLE IF EXISTS COUNTRIES;
DROP TABLE IF EXISTS REGIONS;
DROP TABLE IF EXISTS JOBS;
DROP TABLE IF EXISTS JOB_HISTORY;




CREATE OR REPLACE TABLE EMPLOYEES 
(
    EMPLOYEE_ID NUMBER(6),
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25),
    EMAIL VARCHAR(25),
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE,
    JOB_ID VARCHAR(10),
    SALARY NUMBER(8, 2),
    COMMISSION_PCT NUMBER(2, 2),
    MANAGER_ID NUMBER(6),
    DEPARTMENT_ID NUMBER(4)
);


CREATE OR REPLACE TABLE DEPARTMENTS 
(
    DEPARTMENT_ID NUMBER(4),
    DEPARTMENT_NAME VARCHAR(30),
    MANAGER_ID NUMBER(6),
    LOCATION_ID NUMBER(4)
);

CREATE OR REPLACE TABLE LOCATIONS 
(
    LOCATION_ID NUMBER(4),
    STREET_ADDRESS VARCHAR(40),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(25),
    COUNTRY_ID CHAR(2)
);

CREATE OR REPLACE TABLE COUNTRIES 
(
    COUNTRY_ID CHAR(2),
    COUNTRY_NAME VARCHAR(40),
    REGION_ID NUMBER
);



CREATE OR REPLACE TABLE REGIONS 
(
    REGION_ID NUMBER,
    REGION_NAME VARCHAR(25)
);


CREATE TABLE JOBS 
(
    JOB_ID VARCHAR(10),
    JOB_TITLE VARCHAR(35),
    MIN_SALARY NUMBER(6),
    MAX_SALARY NUMBER(6)
);



CREATE OR REPLACE TABLE JOB_HISTORY 
(
    EMPLOYEE_ID NUMBER(6),
    START_DATE DATE,
    END_DATE DATE,
    JOB_ID VARCHAR(10),
    DEPARTMENT_ID NUMBER(4)
);

SHOW TABLES;