USE DATABASE HRMS

USE SCHEMA HR




TRUNCATE TABLE EMPLOYEES;


INSERT INTO HRMS.HR.EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 100, 'STEVEN', 'KING', 'SKING', '515.123.4567', TO_DATE('17-06-2003', 'DD-MM-YYYY'), 'AD_PRES', 24000, NULL, NULL, 90);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 101, 'NEENA', 'KOCHHAR', 'NKOCHHAR', '515.123.4568', TO_DATE('21-09-2005', 'DD-MM-YYYY'), 'AD_VP', 17000, NULL, 100, 90);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 102, 'LEX', 'DE HAAN', 'LDEHAAN', '515.123.4569', TO_DATE('13-01-2001', 'DD-MM-YYYY'), 'AD_VP', 17000, NULL, 100, 90);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 103, 'ALEXANDER', 'HUNOLD', 'AHUNOLD', '590.423.4567', TO_DATE('03-01-2006', 'DD-MM-YYYY'), 'IT_PROG', 9000, NULL, 102, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 104, 'BRUCE', 'ERNST', 'BERNST', '590.423.4568', TO_DATE('21-05-2007', 'DD-MM-YYYY'), 'IT_PROG', 6000, NULL, 103, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 105, 'DAVID', 'AUSTIN', 'DAUSTIN', '590.423.4569', TO_DATE('25-06-2005', 'DD-MM-YYYY'), 'IT_PROG', 4800, NULL, 103, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 106, 'VALLI', 'PATABALLA', 'VPATABAL', '590.423.4560', TO_DATE('05-02-2006', 'DD-MM-YYYY'), 'IT_PROG', 4800, NULL, 103, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 107, 'DIANA', 'LORENTZ', 'DLORENTZ', '590.423.5567', TO_DATE('07-02-2007', 'DD-MM-YYYY'), 'IT_PROG', 4200, NULL, 103, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 108, 'NANCY', 'GREENBERG', 'NGREENBE', '515.124.4569', TO_DATE('17-08-2002', 'DD-MM-YYYY'), 'FI_MGR', 12008, NULL, 101, 100);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 109, 'DANIEL', 'FAVIET', 'DFAVIET', '515.124.4169', TO_DATE('16-08-2002', 'DD-MM-YYYY'), 'FI_ACCOUNT', 9000, NULL, 108, 100);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 110, 'JOHN', 'CHEN', 'JCHEN', '515.124.4269', TO_DATE('28-09-2005', 'DD-MM-YYYY'), 'FI_ACCOUNT', 8200, NULL, 108, 100);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 111, 'ISMAEL', 'SCIARRA', 'ISCIARRA', '515.124.4369', TO_DATE('30-09-2005', 'DD-MM-YYYY'), 'FI_ACCOUNT', 7700, NULL, 108, 100);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 112, 'JOSE MANUEL', 'URMAN', 'JMURMAN', '515.124.4469', TO_DATE('07-03-2006', 'DD-MM-YYYY'), 'FI_ACCOUNT', 7800, NULL, 108, 100);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 113, 'LUIS', 'POPP', 'LPOPP', '515.124.4567', TO_DATE('07-12-2007', 'DD-MM-YYYY'), 'FI_ACCOUNT', 6900, NULL, 108, 100);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 114, 'DEN', 'RAPHAELY', 'DRAPHEAL', '515.127.4561', TO_DATE('07-12-2002', 'DD-MM-YYYY'), 'PU_MAN', 11000, NULL, 100, 30);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 115, 'ALEXANDER', 'KHOO', 'AKHOO', '515.127.4562', TO_DATE('18-05-2003', 'DD-MM-YYYY'), 'PU_CLERK', 3100, NULL, 114, 30);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 116, 'SHELLI', 'BAIDA', 'SBAIDA', '515.127.4563', TO_DATE('24-12-2005', 'DD-MM-YYYY'), 'PU_CLERK', 2900, NULL, 114, 30);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 117, 'SIGAL', 'TOBIAS', 'STOBIAS', '515.127.4564', TO_DATE('24-07-2005', 'DD-MM-YYYY'), 'PU_CLERK', 2800, NULL, 114, 30);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 118, 'GUY', 'HIMURO', 'GHIMURO', '515.127.4565', TO_DATE('15-11-2006', 'DD-MM-YYYY'), 'PU_CLERK', 2600, NULL, 114, 30);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 119, 'KAREN', 'COLMENARES', 'KCOLMENA', '515.127.4566', TO_DATE('10-08-2007', 'DD-MM-YYYY'), 'PU_CLERK', 2500, NULL, 114, 30);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 120, 'MATTHEW', 'WEISS', 'MWEISS', '650.123.1234', TO_DATE('18-07-2004', 'DD-MM-YYYY'), 'ST_MAN', 8000, NULL, 100, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 121, 'ADAM', 'FRIPP', 'AFRIPP', '650.123.2234', TO_DATE('10-04-2005', 'DD-MM-YYYY'), 'ST_MAN', 8200, NULL, 100, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 122, 'PAYAM', 'KAUFLING', 'PKAUFLIN', '650.123.3234', TO_DATE('01-05-2003', 'DD-MM-YYYY'), 'ST_MAN', 7900, NULL, 100, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 123, 'SHANTA', 'VOLLMAN', 'SVOLLMAN', '650.123.4234', TO_DATE('10-10-2005', 'DD-MM-YYYY'), 'ST_MAN', 6500, NULL, 100, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 124, 'KEVIN', 'MOURGOS', 'KMOURGOS', '650.123.5234', TO_DATE('16-11-2007', 'DD-MM-YYYY'), 'ST_MAN', 5800, NULL, 100, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 125, 'JULIA', 'NAYER', 'JNAYER', '650.124.1214', TO_DATE('16-07-2005', 'DD-MM-YYYY'), 'ST_CLERK', 3200, NULL, 120, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 126, 'IRENE', 'MIKKILINENI', 'IMIKKILI', '650.124.1224', TO_DATE('28-09-2006', 'DD-MM-YYYY'), 'ST_CLERK', 2700, NULL, 120, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 127, 'JAMES', 'LANDRY', 'JLANDRY', '650.124.1334', TO_DATE('14-01-2007', 'DD-MM-YYYY'), 'ST_CLERK', 2400, NULL, 120, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 128, 'STEVEN', 'MARKLE', 'SMARKLE', '650.124.1434', TO_DATE('08-03-2008', 'DD-MM-YYYY'), 'ST_CLERK', 2200, NULL, 120, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 129, 'LAURA', 'BISSOT', 'LBISSOT', '650.124.5234', TO_DATE('20-08-2005', 'DD-MM-YYYY'), 'ST_CLERK', 3300, NULL, 121, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 130, 'MOZHE', 'ATKINSON', 'MATKINSO', '650.124.6234', TO_DATE('30-10-2005', 'DD-MM-YYYY'), 'ST_CLERK', 2800, NULL, 121, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 131, 'JAMES', 'MARLOW', 'JAMRLOW', '650.124.7234', TO_DATE('16-02-2005', 'DD-MM-YYYY'), 'ST_CLERK', 2500, NULL, 121, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 132, 'TJ', 'OLSON', 'TJOLSON', '650.124.8234', TO_DATE('10-04-2007', 'DD-MM-YYYY'), 'ST_CLERK', 2100, NULL, 121, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 133, 'JASON', 'MALLIN', 'JMALLIN', '650.127.1934', TO_DATE('14-06-2004', 'DD-MM-YYYY'), 'ST_CLERK', 3300, NULL, 122, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 134, 'MICHAEL', 'ROGERS', 'MROGERS', '650.127.1834', TO_DATE('26-08-2006', 'DD-MM-YYYY'), 'ST_CLERK', 2900, NULL, 122, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 135, 'KI', 'GEE', 'KGEE', '650.127.1734', TO_DATE('12-12-2007', 'DD-MM-YYYY'), 'ST_CLERK', 2400, NULL, 122, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 136, 'HAZEL', 'PHILTANKER', 'HPHILTAN', '650.127.1634', TO_DATE('06-02-2008', 'DD-MM-YYYY'), 'ST_CLERK', 2200, NULL, 122, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 137, 'RENSKE', 'LADWIG', 'RLADWIG', '650.121.1234', TO_DATE('14-07-2003', 'DD-MM-YYYY'), 'ST_CLERK', 3600, NULL, 123, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 138, 'STEPHEN', 'STILES', 'SSTILES', '650.121.2034', TO_DATE('26-10-2005', 'DD-MM-YYYY'), 'ST_CLERK', 3200, NULL, 123, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 139, 'JOHN', 'SEO', 'JSEO', '650.121.2019', TO_DATE('12-02-2006', 'DD-MM-YYYY'), 'ST_CLERK', 2700, NULL, 123, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 140, 'JOSHUA', 'PATEL', 'JPATEL', '650.121.1834', TO_DATE('06-04-2006', 'DD-MM-YYYY'), 'ST_CLERK', 2500, NULL, 123, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 141, 'TRENNA', 'RAJS', 'TRAJS', '650.121.8009', TO_DATE('17-10-2003', 'DD-MM-YYYY'), 'ST_CLERK', 3500, NULL, 124, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 142, 'CURTIS', 'DAVIES', 'CDAVIES', '650.121.2994', TO_DATE('29-01-2005', 'DD-MM-YYYY'), 'ST_CLERK', 3100, NULL, 124, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 143, 'RANDALL', 'MATOS', 'RMATOS', '650.121.2874', TO_DATE('15-03-2006', 'DD-MM-YYYY'), 'ST_CLERK', 2600, NULL, 124, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 144, 'PETER', 'VARGAS', 'PVARGAS', '650.121.2004', TO_DATE('09-07-2006', 'DD-MM-YYYY'), 'ST_CLERK', 2500, NULL, 124, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 145, 'JOHN', 'RUSSELL', 'JRUSSEL', '011.44.1344.429268', TO_DATE('01-10-2004', 'DD-MM-YYYY'), 'SA_MAN', 14000, .4, 100, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 146, 'KAREN', 'PARTNERS', 'KPARTNER', '011.44.1344.467268', TO_DATE('05-01-2005', 'DD-MM-YYYY'), 'SA_MAN', 13500, .3, 100, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 147, 'ALBERTO', 'ERRAZURIZ', 'AERRAZUR', '011.44.1344.429278', TO_DATE('10-03-2005', 'DD-MM-YYYY'), 'SA_MAN', 12000, .3, 100, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 148, 'GERALD', 'CAMBRAULT', 'GCAMBRAU', '011.44.1344.619268', TO_DATE('15-10-2007', 'DD-MM-YYYY'), 'SA_MAN', 11000, .3, 100, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 149, 'ELENI', 'ZLOTKEY', 'EZLOTKEY', '011.44.1344.429018', TO_DATE('29-01-2008', 'DD-MM-YYYY'), 'SA_MAN', 10500, .2, 100, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 150, 'PETER', 'TUCKER', 'PTUCKER', '011.44.1344.129268', TO_DATE('30-01-2005', 'DD-MM-YYYY'), 'SA_REP', 10000, .3, 145, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 151, 'DAVID', 'BERNSTEIN', 'DBERNSTE', '011.44.1344.345268', TO_DATE('24-03-2005', 'DD-MM-YYYY'), 'SA_REP', 9500, .25, 145, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 152, 'PETER', 'HALL', 'PHALL', '011.44.1344.478968', TO_DATE('20-08-2005', 'DD-MM-YYYY'), 'SA_REP', 9000, .25, 145, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 153, 'CHRISTOPHER', 'OLSEN', 'COLSEN', '011.44.1344.498718', TO_DATE('30-03-2006', 'DD-MM-YYYY'), 'SA_REP', 8000, .2, 145, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 154, 'NANETTE', 'CAMBRAULT', 'NCAMBRAU', '011.44.1344.987668', TO_DATE('09-12-2006', 'DD-MM-YYYY'), 'SA_REP', 7500, .2, 145, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 155, 'OLIVER', 'TUVAULT', 'OTUVAULT', '011.44.1344.486508', TO_DATE('23-11-2007', 'DD-MM-YYYY'), 'SA_REP', 7000, .15, 145, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 156, 'JANETTE', 'KING', 'JKING', '011.44.1345.429268', TO_DATE('30-01-2004', 'DD-MM-YYYY'), 'SA_REP', 10000, .35, 146, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 157, 'PATRICK', 'SULLY', 'PSULLY', '011.44.1345.929268', TO_DATE('04-03-2004', 'DD-MM-YYYY'), 'SA_REP', 9500, .35, 146, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 158, 'ALLAN', 'MCEWEN', 'AMCEWEN', '011.44.1345.829268', TO_DATE('01-08-2004', 'DD-MM-YYYY'), 'SA_REP', 9000, .35, 146, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 159, 'LINDSEY', 'SMITH', 'LSMITH', '011.44.1345.729268', TO_DATE('10-03-2005', 'DD-MM-YYYY'), 'SA_REP', 8000, .3, 146, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 160, 'LOUISE', 'DORAN', 'LDORAN', '011.44.1345.629268', TO_DATE('15-12-2005', 'DD-MM-YYYY'), 'SA_REP', 7500, .3, 146, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 161, 'SARATH', 'SEWALL', 'SSEWALL', '011.44.1345.529268', TO_DATE('03-11-2006', 'DD-MM-YYYY'), 'SA_REP', 7000, .25, 146, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 162, 'CLARA', 'VISHNEY', 'CVISHNEY', '011.44.1346.129268', TO_DATE('11-11-2005', 'DD-MM-YYYY'), 'SA_REP', 10500, .25, 147, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 163, 'DANIELLE', 'GREENE', 'DGREENE', '011.44.1346.229268', TO_DATE('19-03-2007', 'DD-MM-YYYY'), 'SA_REP', 9500, .15, 147, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 164, 'MATTEA', 'MARVINS', 'MMARVINS', '011.44.1346.329268', TO_DATE('24-01-2008', 'DD-MM-YYYY'), 'SA_REP', 7200, .10, 147, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 165, 'DAVID', 'LEE', 'DLEE', '011.44.1346.529268', TO_DATE('23-02-2008', 'DD-MM-YYYY'), 'SA_REP', 6800, .1, 147, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 166, 'SUNDAR', 'ANDE', 'SANDE', '011.44.1346.629268', TO_DATE('24-03-2008', 'DD-MM-YYYY'), 'SA_REP', 6400, .10, 147, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 167, 'AMIT', 'BANDA', 'ABANDA', '011.44.1346.729268', TO_DATE('21-04-2008', 'DD-MM-YYYY'), 'SA_REP', 6200, .10, 147, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 168, 'LISA', 'OZER', 'LOZER', '011.44.1343.929268', TO_DATE('11-03-2005', 'DD-MM-YYYY'), 'SA_REP', 11500, .25, 148, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 169, 'HARRISON', 'BLOOM', 'HBLOOM', '011.44.1343.829268', TO_DATE('23-03-2006', 'DD-MM-YYYY'), 'SA_REP', 10000, .20, 148, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 170, 'TAYLER', 'FOX', 'TFOX', '011.44.1343.729268', TO_DATE('24-01-2006', 'DD-MM-YYYY'), 'SA_REP', 9600, .20, 148, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 171, 'WILLIAM', 'SMITH', 'WSMITH', '011.44.1343.629268', TO_DATE('23-02-2007', 'DD-MM-YYYY'), 'SA_REP', 7400, .15, 148, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 172, 'ELIZABETH', 'BATES', 'EBATES', '011.44.1343.529268', TO_DATE('24-03-2007', 'DD-MM-YYYY'), 'SA_REP', 7300, .15, 148, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 173, 'SUNDITA', 'KUMAR', 'SKUMAR', '011.44.1343.329268', TO_DATE('21-04-2008', 'DD-MM-YYYY'), 'SA_REP', 6100, .10, 148, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 174, 'ELLEN', 'ABEL', 'EABEL', '011.44.1644.429267', TO_DATE('11-05-2004', 'DD-MM-YYYY'), 'SA_REP', 11000, .30, 149, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 175, 'ALYSSA', 'HUTTON', 'AHUTTON', '011.44.1644.429266', TO_DATE('19-03-2005', 'DD-MM-YYYY'), 'SA_REP', 8800, .25, 149, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 176, 'JONATHON', 'TAYLOR', 'JTAYLOR', '011.44.1644.429265', TO_DATE('24-03-2006', 'DD-MM-YYYY'), 'SA_REP', 8600, .20, 149, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 177, 'JACK', 'LIVINGSTON', 'JLIVINGS', '011.44.1644.429264', TO_DATE('23-04-2006', 'DD-MM-YYYY'), 'SA_REP', 8400, .20, 149, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 178, 'KIMBERELY', 'GRANT', 'KGRANT', '011.44.1644.429263', TO_DATE('24-05-2007', 'DD-MM-YYYY'), 'SA_REP', 7000, .15, 149, NULL);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 179, 'CHARLES', 'JOHNSON', 'CJOHNSON', '011.44.1644.429262', TO_DATE('04-01-2008', 'DD-MM-YYYY'), 'SA_REP', 6200, .10, 149, 80);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 180, 'WINSTON', 'TAYLOR', 'WTAYLOR', '650.507.9876', TO_DATE('24-01-2006', 'DD-MM-YYYY'), 'SH_CLERK', 3200, NULL, 120, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 181, 'JEAN', 'FLEAUR', 'JFLEAUR', '650.507.9877', TO_DATE('23-02-2006', 'DD-MM-YYYY'), 'SH_CLERK', 3100, NULL, 120, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 182, 'MARTHA', 'SULLIVAN', 'MSULLIVA', '650.507.9878', TO_DATE('21-06-2007', 'DD-MM-YYYY'), 'SH_CLERK', 2500, NULL, 120, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 183, 'GIRARD', 'GEONI', 'GGEONI', '650.507.9879', TO_DATE('03-02-2008', 'DD-MM-YYYY'), 'SH_CLERK', 2800, NULL, 120, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 184, 'NANDITA', 'SARCHAND', 'NSARCHAN', '650.509.1876', TO_DATE('27-01-2004', 'DD-MM-YYYY'), 'SH_CLERK', 4200, NULL, 121, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 185, 'ALEXIS', 'BULL', 'ABULL', '650.509.2876', TO_DATE('20-02-2005', 'DD-MM-YYYY'), 'SH_CLERK', 4100, NULL, 121, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 186, 'JULIA', 'DELLINGER', 'JDELLING', '650.509.3876', TO_DATE('24-06-2006', 'DD-MM-YYYY'), 'SH_CLERK', 3400, NULL, 121, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 187, 'ANTHONY', 'CABRIO', 'ACABRIO', '650.509.4876', TO_DATE('07-02-2007', 'DD-MM-YYYY'), 'SH_CLERK', 3000, NULL, 121, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 188, 'KELLY', 'CHUNG', 'KCHUNG', '650.505.1876', TO_DATE('14-06-2005', 'DD-MM-YYYY'), 'SH_CLERK', 3800, NULL, 122, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 189, 'JENNIFER', 'DILLY', 'JDILLY', '650.505.2876', TO_DATE('13-08-2005', 'DD-MM-YYYY'), 'SH_CLERK', 3600, NULL, 122, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 190, 'TIMOTHY', 'GATES', 'TGATES', '650.505.3876', TO_DATE('11-07-2006', 'DD-MM-YYYY'), 'SH_CLERK', 2900, NULL, 122, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 191, 'RANDALL', 'PERKINS', 'RPERKINS', '650.505.4876', TO_DATE('19-12-2007', 'DD-MM-YYYY'), 'SH_CLERK', 2500, NULL, 122, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 192, 'SARAH', 'BELL', 'SBELL', '650.501.1876', TO_DATE('04-02-2004', 'DD-MM-YYYY'), 'SH_CLERK', 4000, NULL, 123, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 193, 'BRITNEY', 'EVERETT', 'BEVERETT', '650.501.2876', TO_DATE('03-03-2005', 'DD-MM-YYYY'), 'SH_CLERK', 3900, NULL, 123, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 194, 'SAMUEL', 'MCCAIN', 'SMCCAIN', '650.501.3876', TO_DATE('01-07-2006', 'DD-MM-YYYY'), 'SH_CLERK', 3200, NULL, 123, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 195, 'VANCE', 'JONES', 'VJONES', '650.501.4876', TO_DATE('17-03-2007', 'DD-MM-YYYY'), 'SH_CLERK', 2800, NULL, 123, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 196, 'ALANA', 'WALSH', 'AWALSH', '650.507.9811', TO_DATE('24-04-2006', 'DD-MM-YYYY'), 'SH_CLERK', 3100, NULL, 124, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 197, 'KEVIN', 'FEENEY', 'KFEENEY', '650.507.9822', TO_DATE('23-05-2006', 'DD-MM-YYYY'), 'SH_CLERK', 3000, NULL, 124, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 198, 'DONALD', 'OCONNELL', 'DOCONNEL', '650.507.9833', TO_DATE('21-06-2007', 'DD-MM-YYYY'), 'SH_CLERK', 2600, NULL, 124, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 199, 'DOUGLAS', 'GRANT', 'DGRANT', '650.507.9844', TO_DATE('13-01-2008', 'DD-MM-YYYY'), 'SH_CLERK', 2600, NULL, 124, 50);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 200, 'JENNIFER', 'WHALEN', 'JWHALEN', '515.123.4444', TO_DATE('17-09-2003', 'DD-MM-YYYY'), 'AD_ASST', 4400, NULL, 101, 10);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 201, 'MICHAEL', 'HARTSTEIN', 'MHARTSTE', '515.123.5555', TO_DATE('17-02-2004', 'DD-MM-YYYY'), 'MK_MAN', 13000, NULL, 100, 20);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 202, 'PAT', 'FAY', 'PFAY', '603.123.6666', TO_DATE('17-08-2005', 'DD-MM-YYYY'), 'MK_REP', 6000, NULL, 201, 20);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 203, 'SUSAN', 'MAVRIS', 'SMAVRIS', '515.123.7777', TO_DATE('07-06-2002', 'DD-MM-YYYY'), 'HR_REP', 6500, NULL, 101, 40);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 204, 'HERMANN', 'BAER', 'HBAER', '515.123.8888', TO_DATE('07-06-2002', 'DD-MM-YYYY'), 'PR_REP', 10000, NULL, 101, 70);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 205, 'SHELLEY', 'HIGGINS', 'SHIGGINS', '515.123.8080', TO_DATE('07-06-2002', 'DD-MM-YYYY'), 'AC_MGR', 12008, NULL, 101, 110);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 206, 'WILLIAM', 'GIETZ', 'WGIETZ', '515.123.8181', TO_DATE('07-06-2002', 'DD-MM-YYYY'), 'AC_ACCOUNT', 8300, NULL, 205, 110);


TRUNCATE TABLE DEPARTMENTS;

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 10, 'ADMINISTRATION', 200, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 20, 'MARKETING', 201, 1800);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 30, 'PURCHASING', 114, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 40, 'HUMAN RESOURCES', 203, 2400);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 50, 'SHIPPING', 121, 1500);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 60, 'IT', 103, 1400);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 70, 'PUBLIC RELATIONS', 204, 2700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 80, 'SALES', 145, 2500);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 90, 'EXECUTIVE', 100, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 100, 'FINANCE', 108, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 110, 'ACCOUNTING', 205, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 120, 'TREASURY', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 130, 'CORPORATE TAX', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 140, 'CONTROL AND CREDIT', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 150, 'SHAREHOLDER SERVICES', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 160, 'BENEFITS', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 170, 'MANUFACTURING', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 180, 'CONSTRUCTION', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 190, 'CONTRACTING', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 200, 'OPERATIONS', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 210, 'IT SUPPORT', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 220, 'NOC', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 230, 'IT HELPDESK', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 240, 'GOVERNMENT SALES', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 250, 'RETAIL SALES', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 260, 'RECRUITING', NULL, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES
( 270, 'PAYROLL', NULL, 1700);


TRUNCATE TABLE LOCATIONS;

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
(1000 , '1297 VIA COLA DI RIE', '00989', 'ROMA', NULL, 'IT');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
(1100, '93091 CALLE DELLA TESTA', '10934', 'VENICE', NULL, 'IT');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
(1200, '2017 SHINJUKU-KU', '1689', 'TOKYO', 'TOKYO PREFECTURE', 'JP');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
(1300, '9450 KAMIYA-CHO', '6823', 'HIROSHIMA', NULL, 'JP');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
(1400, '2014 JABBERWOCKY RD', '26192', 'SOUTHLAKE', 'TEXAS', 'US');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 1500, '2011 INTERIORS BLVD', '99236', 'SOUTH SAN FRANCISCO', 'CALIFORNIA', 'US');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 1600, '2007 ZAGORA ST', '50090', 'SOUTH BRUNSWICK', 'NEW JERSEY', 'US');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 1700, '2004 CHARADE RD', '98199', 'SEATTLE', 'WASHINGTON', 'US');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 1800, '147 SPADINA AVE', 'M5V 2L7', 'TORONTO', 'ONTARIO', 'CA');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 1900, '6092 BOXWOOD ST', 'YSW 9T2', 'WHITEHORSE', 'YUKON', 'CA');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2000, '40-5-12 LAOGIANGGEN', '190518', 'BEIJING', NULL, 'CN');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2100, '1298 VILEPARLE (E)', '490231', 'BOMBAY', 'MAHARASHTRA', 'IN');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2200, '12-98 VICTORIA STREET', '2901', 'SYDNEY', 'NEW SOUTH WALES', 'AU');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2300, '198 CLEMENTI NORTH', '540198', 'SINGAPORE', NULL, 'SG');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2400, '8204 ARTHUR ST', NULL, 'LONDON', NULL, 'UK');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2500, 'MAGDALEN CENTRE, THE OXFORD SCIENCE PARK', 'OX9 9ZB', 'OXFORD', 'OXFORD', 'UK');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2600, '9702 CHESTER ROAD', '09629850293', 'STRETFORD', 'MANCHESTER', 'UK');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2700, 'SCHWANTHALERSTR. 7031', '80925', 'MUNICH', 'BAVARIA', 'DE');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2800, 'RUA FREI CANECA 1360 ', '01307-002', 'SAO PAULO', 'SAO PAULO', 'BR');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 2900, '20 RUE DES CORPS-SAINTS', '1730', 'GENEVA', 'GENEVE', 'CH');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 3000, 'MURTENSTRASSE 921', '3095', 'BERN', 'BE', 'CH');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 3100, 'PIETER BREUGHELSTRAAT 837', '3029SK', 'UTRECHT', 'UTRECHT', 'NL');

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES
( 3200, 'MARIANO ESCOBEDO 9991', '11932', 'MEXICO CITY', 'DISTRITO FEDERAL,', 'MX');



TRUNCATE TABLE REGIONS;

INSERT INTO REGIONS (REGION_ID, REGION_NAME) VALUES (1, 'EUROPE');
INSERT INTO REGIONS (REGION_ID, REGION_NAME) VALUES (2, 'AMERICAS');
INSERT INTO REGIONS (REGION_ID, REGION_NAME) VALUES (3, 'ASIA');
INSERT INTO REGIONS (REGION_ID, REGION_NAME) VALUES (4, 'MIDDLE EAST AND AFRICA');


TRUNCATE TABLE COUNTRIES;

INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('IT', 'ITALY', 1);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('JP', 'JAPAN', 3);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('US', 'UNITED STATES OF AMERICA', 2);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('CA', 'CANADA', 2);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('CN', 'CHINA', 3);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('IN', 'INDIA', 3);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('AU', 'AUSTRALIA', 3);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('ZW', 'ZIMBABWE', 4);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('SG', 'SINGAPORE', 3);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('UK', 'UNITED KINGDOM', 1);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('FR', 'FRANCE', 1);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('DE', 'GERMANY', 1);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('ZM', 'ZAMBIA', 4);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('EG', 'EGYPT', 4);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('BR', 'BRAZIL', 2);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('CH', 'SWITZERLAND', 1);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('NL', 'NETHERLANDS', 1);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('MX', 'MEXICO', 2);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('KW', 'KUWAIT', 4);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('IL', 'ISRAEL', 4);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('DK', 'DENMARK', 1);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('ML', 'MALAYSIA', 3);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('NG', 'NIGERIA', 4);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('AR', 'ARGENTINA', 2);
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('BE', 'BELGIUM', 1);




TRUNCATE TABLE JOBS;


INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('AD_PRES', 'PRESIDENT', 20080, 40000);
 
INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('AD_VP', 'ADMINISTRATION VICE PRESIDENT', 15000, 30000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('AD_ASST', 'ADMINISTRATION ASSISTANT', 3000, 6000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('FI_MGR', 'FINANCE MANAGER', 8200, 16000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('FI_ACCOUNT', 'ACCOUNTANT', 4200, 9000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('AC_MGR', 'ACCOUNTING MANAGER', 8200, 16000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('AC_ACCOUNT', 'PUBLIC ACCOUNTANT', 4200, 9000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('SA_MAN', 'SALES MANAGER', 10000, 20080);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('SA_REP', 'SALES REPRESENTATIVE', 6000, 12008);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('PU_MAN', 'PURCHASING MANAGER', 8000, 15000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('PU_CLERK', 'PURCHASING CLERK', 2500, 5500);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('ST_MAN', 'STOCK MANAGER', 5500, 8500);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('ST_CLERK', 'STOCK CLERK', 2008, 5000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('SH_CLERK', 'SHIPPING CLERK', 2500, 5500);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('IT_PROG', 'PROGRAMMER', 4000, 10000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('MK_MAN', 'MARKETING MANAGER', 9000, 15000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('MK_REP', 'MARKETING REPRESENTATIVE', 4000, 9000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('HR_REP', 'HUMAN RESOURCES REPRESENTATIVE', 4000, 9000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES ('PR_REP', 'PUBLIC RELATIONS REPRESENTATIVE', 4500, 10500);



TRUNCATE TABLE JOB_HISTORY;

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (102, TO_DATE('13-01-2001', 'DD-MM-YYYY'), TO_DATE('24-07-2006', 'DD-MM-YYYY'), 'IT_PROG', 60);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (101, TO_DATE('21-09-1997', 'DD-MM-YYYY'), TO_DATE('27-10-2001', 'DD-MM-YYYY'), 'AC_ACCOUNT', 110);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (101, TO_DATE('28-10-2001', 'DD-MM-YYYY'), TO_DATE('15-03-2005', 'DD-MM-YYYY'), 'AC_MGR', 110);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (201, TO_DATE('17-02-2004', 'DD-MM-YYYY'), TO_DATE('19-12-2007', 'DD-MM-YYYY'), 'MK_REP', 20);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES  (114, TO_DATE('24-03-2006', 'DD-MM-YYYY'), TO_DATE('31-12-2007', 'DD-MM-YYYY'), 'ST_CLERK', 50);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES  (122, TO_DATE('01-01-2007', 'DD-MM-YYYY'), TO_DATE('31-12-2007', 'DD-MM-YYYY'), 'ST_CLERK', 50);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES  (200, TO_DATE('17-09-1995', 'DD-MM-YYYY'), TO_DATE('17-06-2001', 'DD-MM-YYYY'), 'AD_ASST', 90);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES  (176, TO_DATE('24-03-2006', 'DD-MM-YYYY'), TO_DATE('31-12-2006', 'DD-MM-YYYY'), 'SA_REP', 80);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES  (176, TO_DATE('01-01-2007', 'DD-MM-YYYY'), TO_DATE('31-12-2007', 'DD-MM-YYYY'), 'SA_MAN', 80);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES  (200, TO_DATE('01-07-2002', 'DD-MM-YYYY'), TO_DATE('31-12-2006', 'DD-MM-YYYY'), 'AC_ACCOUNT', 90);


SELECT COUNT(*),'REGIONS' FROM REGIONS
UNION ALL
SELECT COUNT(*),'COUNTRIES' FROM COUNTRIES
UNION ALL
SELECT COUNT(*),'LOCATIONS' FROM LOCATIONS
UNION ALL
SELECT COUNT(*),'JOB_HISTORY' FROM JOB_HISTORY
UNION ALL
SELECT COUNT(*),'DEPARTMENTS' FROM DEPARTMENTS
UNION ALL
SELECT COUNT(*),'EMPLOYEES' FROM EMPLOYEES
UNION ALL
SELECT COUNT(*),'JOBS' FROM JOBS;