USE DATABASE HRMS;

USE SCHEMA PIPE;


CREATE OR REPLACE FILE FORMAT HRMS.PIPE.CSV_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0
NULL_IF = ('NULL','Null','null') 
FIELD_OPTIONALLY_ENCLOSED_BY = '"'        
EMPTY_FIELD_AS_NULL = TRUE;


CREATE OR REPLACE STAGE HRMS.PIPE.AWS_PIPE_CSV_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://learn2cloud-snowflake/snowpipe/csv/'
FILE_FORMAT = CSV_PIPE_FILEFORMAT;


LIST @AWS_PIPE_CSV_STAGE



CREATE OR REPLACE TABLE HRMS.PIPE.EMPLOYEES_SNOWPIPE_CSV_ERROR 
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      DATE ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);




CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV_ERROR
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV_ERROR FROM @AWS_PIPE_CSV_STAGE;




SHOW PIPES; 

SHOW PIPES LIKE 'PIPE_EMPLOYEES_CSV_ERROR';


SELECT SYSTEM$PIPE_STATUS ('PIPE_EMPLOYEES_CSV_ERROR');


SELECT * FROM PIPE_EMPLOYEES_CSV_ERROR;

SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY
        (
        TABLE_NAME=>'EMPLOYEES_SNOWPIPE_CSV_ERROR', 
        START_TIME=> DATEADD(HOURS, -4, CURRENT_TIMESTAMP()))
        );


SELECT * FROM TABLE(INFORMATION_SCHEMA.VALIDATE_PIPE_LOAD
(PIPE_NAME =>'PIPE_EMPLOYEES_CSV_ERROR',
 START_TIME=> DATEADD(HOURS, -4, CURRENT_TIMESTAMP()))
 );



SELECT * FROM EMPLOYEES_SNOWPIPE_CSV_ERROR;