SELECT * FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
			 DATE_RANGE_START  =>TO_TIMESTAMP_TZ('2024-07-03 00:00:00.000 -0700'),
			 DATE_RANGE_END    =>TO_TIMESTAMP_TZ('2024-07-19 00:00:00.000 -0700')));


 SELECT *
        FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
        DATE_RANGE_START=>DATEADD('DAY',-12,CURRENT_DATE()),
        DATE_RANGE_END => CURRENT_DATE()   
        ));    



 SELECT *
        FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
        DATE_RANGE_START=>DATEADD('HOUR',-6,CURRENT_DATE())));    



SELECT  * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY
ORDER BY 3 DESC


 SELECT *
   FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
     DATE_RANGE_START=>DATEADD('DAY',-14,CURRENT_DATE()),
     DATE_RANGE_END=>CURRENT_DATE()))