USE DATABASE HRMS;


CREATE OR REPLACE SCHEMA PIPE;


CREATE OR REPLACE FILE FORMAT HRMS.PIPE.CSV_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0
NULL_IF = ('NULL','Null','null') 
FIELD_OPTIONALLY_ENCLOSED_BY = '"'        
EMPTY_FIELD_AS_NULL = TRUE;




CREATE OR REPLACE STAGE HRMS.PIPE.AWS_PIPE_CSV_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://learn2cloud-snowflake/snowpipe/csv/'
FILE_FORMAT = CSV_PIPE_FILEFORMAT;


LIST @AWS_PIPE_CSV_STAGE


SELECT 
        T.$1, 
        T.$2, 
        T.$3,
        T.$4, 
        T.$5, 
        T.$6 , 
        T.$7, 
        T.$8,
        T.$9,
        T.$10, 
        T.$11,
        METADATA$FILENAME
FROM @AWS_PIPE_CSV_STAGE T;




CREATE OR REPLACE TABLE EMPLOYEES_SNOWPIPE_CSV 
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);


CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE;


SHOW PIPES LIKE 'PIPE_EMPLOYEES_CSV';

SHOW PIPES;



SELECT SYSTEM$PIPE_STATUS ('PIPE_EMPLOYEES_CSV');



LIST @AWS_PIPE_CSV_STAGE;


SELECT * FROM EMPLOYEES_SNOWPIPE_CSV;


ALTER PIPE PIPE_EMPLOYEES_CSV REFRESH;


SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY
        (
        TABLE_NAME=>'EMPLOYEES_SNOWPIPE_CSV', 
        START_TIME=> DATEADD(HOURS, -4, CURRENT_TIMESTAMP()))
        );



ALTER PIPE HRMS.PIPE.PIPE_EMPLOYEES_CSV SET PIPE_EXECUTION_PAUSED=TRUE;


SELECT SYSTEM$PIPE_STATUS ('PIPE_EMPLOYEES_CSV');


SELECT SYSTEM$PIPE_FORCE_RESUME('PIPE_EMPLOYEES_CSV')

ALTER PIPE HRMS.PIPE.PIPE_EMPLOYEES_CSV SET PIPE_EXECUTION_PAUSED=FALSE;




CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
ON_ERROR = 'ABORT_STATEMENT'

CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
ON_ERROR = 'SKIP_FILE'

CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
ON_ERROR = 'CONTINUE'

CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
VALIDATION_MODE ='RETURN_ALL_ERRORS'


CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
FILES =('employees_part_005')

CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
FORCE=TRUE

CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
PURGE=TRUE

CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
SIZE_LIMIT = 2000


CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
RETURN_FAILED_ONLY = TRUE


CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
VALIDATION_MODE = 'RETURN_ERRORS'























--Copy Options
---------------

CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
PATTERN='.*employees.*[.]csv'


CREATE OR REPLACE PIPE PIPE_EMPLOYEES_CSV
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE_CSV FROM @AWS_PIPE_CSV_STAGE
ON_ERROR = 'ABORT_STATEMENT'