USE DATABASE HRMS;

USE SCHEMA HR;

SELECT * FROM HRMS.HR.EMPLOYEES_MASK


CREATE  OR REPLACE MASKING POLICY MASK_SALARY_CONDITIONAL AS (MASK_COL NUMBER(8,2),CONDITION_COL STRING) 
RETURNS  NUMBER(8,2) ->
CASE 
    WHEN CONDITION_COL LIKE 'AD%' THEN -1
    ELSE MASK_COL        
END



ALTER TABLE EMPLOYEES_MASK MODIFY COLUMN SALARY SET MASKING POLICY MASK_SALARY_CONDITIONAL USING (SALARY,JOB_ID) 




ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN SALARY UNSET MASKING POLICY;


SELECT * FROM EMPLOYEES_MASK


DROP TABLE HRMS.HR.EMPLOYEES_MASK;

SHOW MASKING POLICIES;