USE DATABASE HRMS;

USE SCHEMA HR;

CREATE OR REPLACE TABLE EMPLOYEES_MASK
(
    EMPLOYEE_ID         NUMBER(6),
    FIRST_NAME          VARCHAR(20),
    LAST_NAME           VARCHAR(25),
    EMAIL               VARCHAR(25),
    PHONE_NUMBER        VARCHAR(80),
    DATE_OF_BIRTH       DATE,
    SSN                 NUMBER,
    JOB_ID              VARCHAR(10),
    SALARY              NUMBER(8, 2),
    COMMISSION_PCT      NUMBER(2, 2),
    MANAGER_ID          NUMBER(6),
    DEPARTMENT_ID       NUMBER(4)
);


INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 100, 'STEVEN', 'KING', 'SKING', '515.123.4567', TO_DATE('17-06-1983', 'DD-MM-YYYY') ,865508880 ,'AD_PRES', 24000, NULL, NULL, 90);

INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 101, 'NEENA', 'KOCHHAR', 'NKOCHHAR', '847.123.4568', TO_DATE('27-01-1987', 'DD-MM-YYYY') ,532049173 , 'AD_VP', 17000, NULL, 100, 90);

INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 102, 'LEX', 'DE HAAN', 'LDEHAAN', '515.123.456', TO_DATE('12-04-1989', 'DD-MM-YYYY') ,732048471 , 'AD_VP', 17000, NULL, 100, 90);

INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 103, 'ALEXANDER', 'HUNOLD', 'AHUNOLD', '590.423.4567', TO_DATE('15-05-1990', 'DD-MM-YYYY') ,752407536 ,'IT_PROG', 9000, NULL, 102, 60);

INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 104, 'BRUCE', 'ERNST', 'BERNST', '590.423.4568',TO_DATE('17-06-1993', 'DD-MM-YYYY') ,541962382 , 'IT_PROG', 6000, NULL, 103, 60);

INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 105, 'DAVID', 'AUSTIN', 'DAUSTIN', '590.423.4569',TO_DATE('17-06-1995', 'DD-MM-YYYY') ,168016654 , 'IT_PROG', 4800, NULL, 103, 60);

INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 107, 'DIANA', 'LORENTZ', 'DLORENTZ', '590.423.5567', TO_DATE('17-06-2000', 'DD-MM-YYYY') ,193647385 , 'IT_PROG', 4200, NULL, 103, 60);

INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 108, 'NANCY', 'GREENBERG', 'NGREENBE', '515.124.4569',TO_DATE('17-06-2005', 'DD-MM-YYYY') ,100821635 , 'FI_MGR', 12008, NULL, 101, 100);

INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 109, 'DANIEL', 'FAVIET', 'DFAVIET', '515.124.4169', TO_DATE('17-06-2003', 'DD-MM-YYYY') ,461788738 , 'FI_ACCOUNT', 9000, NULL, 108, 100);

INSERT INTO HRMS.HR.EMPLOYEES_MASK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, SSN , JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 110, 'JOHN', 'CHEN', 'JCHEN', '515.124.4269', TO_DATE('17-06-2008', 'DD-MM-YYYY') ,589329706 , 'FI_ACCOUNT', 8200, NULL, 108, 100);


SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

SELECT CURRENT_USER();

CREATE OR REPLACE ROLE ROLE_BI_DEVELOPER; 

GRANT USAGE ON DATABASE  HRMS           TO ROLE ROLE_BI_DEVELOPER;
GRANT USAGE ON SCHEMA    HRMS.HR        TO ROLE ROLE_BI_DEVELOPER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH     TO ROLE ROLE_BI_DEVELOPER;
GRANT SELECT ON TABLE HR.EMPLOYEES_MASK TO ROLE ROLE_BI_DEVELOPER;

CREATE OR REPLACE ROLE ROLE_DATA_ENGINEER; 

GRANT USAGE ON DATABASE  HRMS           TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON SCHEMA    HRMS.HR        TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH     TO ROLE ROLE_DATA_ENGINEER;
GRANT SELECT ON TABLE HR.EMPLOYEES_MASK TO ROLE ROLE_DATA_ENGINEER;

CREATE OR REPLACE ROLE ROLE_SNOWFLAKE_DA;   

GRANT USAGE ON DATABASE  HRMS           TO ROLE ROLE_SNOWFLAKE_DA;
GRANT USAGE ON SCHEMA    HRMS.HR        TO ROLE ROLE_SNOWFLAKE_DA;
GRANT USAGE ON WAREHOUSE COMPUTE_WH     TO ROLE ROLE_SNOWFLAKE_DA;
GRANT SELECT ON TABLE HR.EMPLOYEES_MASK TO ROLE ROLE_SNOWFLAKE_DA;

CREATE OR REPLACE ROLE ROLE_SNOWFLAKE_DBA; DROP ROLE ROLE_SNOWFLAKE_DBA

GRANT USAGE ON DATABASE  HRMS           TO ROLE ROLE_SNOWFLAKE_DBA;
GRANT USAGE ON SCHEMA    HRMS.HR        TO ROLE ROLE_SNOWFLAKE_DBA;
GRANT USAGE ON WAREHOUSE COMPUTE_WH     TO ROLE ROLE_SNOWFLAKE_DBA;
GRANT SELECT ON TABLE HR.EMPLOYEES_MASK TO ROLE ROLE_SNOWFLAKE_DBA;

SELECT CURRENT_USER();


GRANT ROLE ROLE_BI_DEVELOPER  TO USER SNAIR25;
GRANT ROLE ROLE_DATA_ENGINEER TO USER SNAIR25;
GRANT ROLE ROLE_SNOWFLAKE_DA  TO USER SNAIR25;
GRANT ROLE ROLE_SNOWFLAKE_DBA TO USER SNAIR25;


SELECT * FROM HRMS.HR.EMPLOYEES_MASK;



SELECT CURRENT_ROLE();

CREATE OR REPLACE MASKING POLICY MASK_PHONE_NUMBER AS (VAL VARCHAR) 
RETURNS VARCHAR ->
  CASE
    WHEN CURRENT_ROLE() ='ROLE_DATA_ENGINEER' THEN VAL
    ELSE '#######################'
  END

SELECT * FROM HRMS.HR.EMPLOYEES_MASK

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER SET MASKING POLICY MASK_PHONE_NUMBER;

SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

USE ROLE ROLE_DATA_ENGINEER;

USE ROLE ACCOUNTADMIN;


CREATE OR REPLACE MASKING POLICY MASK_PHONE_NUMBER AS (VAL STRING) 
RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_ENGINEER','ROLE_BI_DEVELOPER') THEN VAL
    ELSE '#######################'
END;


DROP MASKING POLICY MASK_PHONE_NUMBER;


ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER UNSET MASKING POLICY;
  
ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER SET MASKING POLICY MASK_PHONE_NUMBER;
  
SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

USE ROLE ROLE_BI_DEVELOPER;

USE ROLE ACCOUNTADMIN;


CREATE OR REPLACE MASKING POLICY MASK_PHONE_NUMBER AS (VAL STRING) 
RETURNS STRING ->
 CASE
    WHEN CURRENT_ROLE() IN ('ROLE_BI_DEVELOPER') THEN VAL
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_ENGINEER')  THEN SUBSTRING(VAL,1,3)||'******' 
    ELSE '#######################'
END;


ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER UNSET MASKING POLICY;

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER SET MASKING POLICY MASK_PHONE_NUMBER;  

SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

USE ROLE ACCOUNTADMIN;

USE ROLE ROLE_BI_DEVELOPER

USE ROLE ROLE_DATA_ENGINEER

SELECT * FROM HRMS.HR.EMPLOYEES_MASK;


CREATE OR REPLACE MASKING POLICY MASK_PHONE_NUMBER AS (VAL STRING) 
RETURNS STRING ->
 CASE
    WHEN CURRENT_ROLE() IN ('ROLE_BI_DEVELOPER') THEN VAL
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_ENGINEER')  THEN 
        CASE
             WHEN SUBSTRING(VAL,1,3) ='515' THEN '515.000.0000'
             WHEN SUBSTRING(VAL,1,3) ='590' THEN '590.111.1111'
        ELSE '000.000.0000'
        END
 ELSE '*****'
END

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER UNSET MASKING POLICY;

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER SET MASKING POLICY MASK_PHONE_NUMBER;  

SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

USE ROLE ROLE_DATA_ENGINEER
USE ROLE ACCOUNTADMIN

CREATE OR REPLACE FUNCTION UDF_MASK_PHONE(in_phone_number STRING)
RETURNS STRING
AS
$$ 
    SELECT  SUBSTRING(LEFT(ABS(RANDOM()),10),1,3)||'.'||SUBSTRING(LEFT(ABS(RANDOM()),10),4,3) ||'.'||SUBSTRING(LEFT(ABS(RANDOM()),10),-4)
$$

CREATE OR REPLACE MASKING POLICY MASK_PHONE_NUMBER AS (VAL STRING) 
RETURNS STRING ->
 CASE
    WHEN CURRENT_ROLE() IN ('ROLE_BI_DEVELOPER')   THEN VAL
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_ENGINEER')  THEN UDF_MASK_PHONE(VAL)        
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN')        THEN SHA2(VAL)        
 ELSE '*****'
END;

SELECT SHA2('Texas') , LENGTH(SHA2('Texas'))

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER UNSET MASKING POLICY;

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER SET MASKING POLICY MASK_PHONE_NUMBER;  

SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

USE ROLE ROLE_DATA_ENGINEER
USE ROLE ACCOUNTADMIN
USE ROLE ROLE_BI_DEVELOPER

CREATE OR REPLACE MASKING POLICY MASK_DATE_OF_BIRTH AS (VAL DATE) 
RETURNS DATE ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_BI_DEVELOPER')  THEN VAL
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_ENGINEER') THEN TO_DATE('1900-01-01','YYYY-MM-DD')
    ELSE TO_DATE('9999-01-01','YYYY-MM-DD')
END

USE ROLE ROLE_DATA_ENGINEER
USE ROLE ROLE_BI_DEVELOPER
USE ROLE ACCOUNTADMIN

SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN DATE_OF_BIRTH SET MASKING POLICY MASK_DATE_OF_BIRTH;  

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN DATE_OF_BIRTH UNSET MASKING POLICY;

USE ROLE ROLE_DATA_ENGINEER 

CREATE OR REPLACE MASKING POLICY MASK_NEW_DATE_OF_BIRTH AS (VAL DATE) 
RETURNS DATE ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_BI_DEVELOPER')  THEN VAL
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_ENGINEER') THEN TO_DATE('1900-01-01','YYYY-MM-DD')
    ELSE TO_DATE('9999-01-01','YYYY-MM-DD')
END


ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN DATE_OF_BIRTH SET MASKING POLICY MASK_NEW_DATE_OF_BIRTH;  

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN DATE_OF_BIRTH UNSET MASKING POLICY;


SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN HIRE_DATE SET MASKING POLICY MASK_DATE_OF_BIRTH;  


SELECT * FROM HRMS.HR.EMPLOYEES_MASK;


CREATE OR REPLACE MASKING POLICY MASK_SSN AS (VAL NUMBER) 
RETURNS NUMBER ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_BI_DEVELOPER')  THEN VAL
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_ENGINEER') THEN ABS(RANDOM())
    ELSE 111111111
END;

USE ROLE ACCOUNTADMIN
USE ROLE ROLE_BI_DEVELOPER
USE ROLE ROLE_DATA_ENGINEER

SELECT * FROM HRMS.HR.EMPLOYEES_MASK;  

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN SSN SET MASKING POLICY MASK_SSN;  

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN SSN UNSET MASKING POLICY;


SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

USE ROLE ACCOUNTADMIN

SHOW MASKING POLICIES

SELECT * FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME=>'MASK_SSN'))

DESC MASKING POLICY MASK_SSN

DESCRIBE TABLE HRMS.HR.EMPLOYEES_MASK;


CREATE OR REPLACE TABLE HRMS.HR.EMPLOYEES_MASK_MULTIPLE
(
    EMPLOYEE_ID         NUMBER(6),
    FIRST_NAME          VARCHAR(20),
    LAST_NAME           VARCHAR(25),
    EMAIL               VARCHAR(25),
    PHONE_NUMBER        VARCHAR(80),
    DATE_OF_BIRTH       DATE,
    SSN                 NUMBER,
    JOB_ID              VARCHAR(10),
    SALARY              NUMBER(8, 2),
    COMMISSION_PCT      NUMBER(2, 2),
    MANAGER_ID          NUMBER(6),
    DEPARTMENT_ID       NUMBER(4)
);


ALTER TABLE HRMS.HR.EMPLOYEES_MASK_MULTIPLE MODIFY COLUMN SSN SET MASKING POLICY MASK_SSN;  

SELECT * FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME=>'MASK_SSN'))

DESCRIBE TABLE HRMS.HR.EMPLOYEES_MASK;


ALTER MASKING POLICY MASK_SSN SET BODY ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_BI_DEVELOPER')  THEN VAL
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_ENGINEER','ACCOUNTADMIN') THEN  ABS(RANDOM())
    ELSE 111111111
END;

DESC MASKING POLICY MASK_SSN

SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

SELECT * FROM HRMS.HR.EMPLOYEES_MASK
WHERE DATE_OF_BIRTH LIKE '%20%'

SELECT * FROM HRMS.HR.EMPLOYEES_MASK
WHERE DATE_OF_BIRTH LIKE '%9999%'


CREATE OR REPLACE TABLE HRMS.HR.EMPLOYEES_CTAS
AS
SELECT * FROM HRMS.HR.EMPLOYEES_MASK;


SELECT * FROM HRMS.HR.EMPLOYEES_CTAS

DESCRIBE TABLE EMPLOYEES_CTAS

USE ROLE ACCOUNTADMIN;

SHOW MASKING POLICIES;

ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN DATE_OF_BIRTH UNSET MASKING POLICY;
ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN PHONE_NUMBER  UNSET MASKING POLICY;
ALTER TABLE HRMS.HR.EMPLOYEES_MASK MODIFY COLUMN SSN           UNSET MASKING POLICY;


SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

CREATE OR REPLACE VIEW VIEW_EMPLOYEES_MASK 
AS
SELECT * FROM HRMS.HR.EMPLOYEES_MASK;

SELECT * FROM VIEW_EMPLOYEES



CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS (VAL VARCHAR) 
RETURNS VARCHAR ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_BI_DEVELOPER')  THEN VAL
    ELSE   LEFT(VAL,2)||'********'
END;

ALTER VIEW VIEW_EMPLOYEES  MODIFY COLUMN EMAIL SET MASKING POLICY MASK_EMAIL;  

ALTER VIEW HRMS.HR.VIEW_EMPLOYEES MODIFY COLUMN EMAIL UNSET MASKING POLICY;


SELECT * FROM VIEW_EMPLOYEES;



SELECT FIRST_NAME, LAST_NAME,EMAIL,SSN,DATE_OF_BIRTH, FROM HRMS.HR.EMPLOYEES_MASK;