
USE DATABASE HRMS;

CREATE OR REPLACE SCHEMA CLUSTER;

CREATE OR REPLACE TABLE EMPLOYEES (
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      DATE ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
) --CLUSTER BY (HIRE_DATE,JOB_ID);



INSERT INTO HRMS.CLUSTER.EMPLOYEES
SELECT E1.* FROM  
                   HRMS.HR.EMPLOYEES E1,
                   HRMS.HR.EMPLOYEES E2,
                   HRMS.HR.EMPLOYEES E3,
                   HRMS.HR.EMPLOYEES E4; 
                   
SELECT COUNT(*) FROM EMPLOYEES;
                   

ALTER SESSION SET USE_CACHED_RESULT = FALSE;



SELECT COUNT(*),SUM(SALARY) FROM HRMS.CLUSTER.EMPLOYEES 
WHERE HIRE_DATE BETWEEN '2003-06-17' AND '2006-02-05'
AND JOB_ID='SA_REP';

ALTER TABLE HRMS.CLUSTER.EMPLOYEES CLUSTER BY (HIRE_DATE,JOB_ID);


SELECT COUNT(*),SUM(SALARY) FROM EMPLOYEES 
WHERE HIRE_DATE BETWEEN '2003-06-17' AND '2006-02-05'
AND JOB_ID='SA_REP';
              
ALTER TABLE HRMS.CLUSTER.EMPLOYEES CLUSTER BY (YEAR(HIRE_DATE),JOB_ID);               
               
SELECT COUNT(*),SUM(SALARY) FROM EMPLOYEES 
WHERE YEAR(HIRE_DATE) =2006