USE DATABASE HRMS;

CREATE OR REPLACE SCHEMA MATVIEW;


CREATE OR REPLACE TABLE EMPLOYEES 
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      DATE ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
) 
CLUSTER BY (DEPARTMENT_ID,JOB_ID);



INSERT INTO HRMS.MATVIEW.EMPLOYEES
SELECT E1.* FROM  
                   HRMS.HR.EMPLOYEES E1,
                   HRMS.HR.EMPLOYEES E2,
                   HRMS.HR.EMPLOYEES E3,
                   HRMS.HR.EMPLOYEES E4; 
                   
ALTER SESSION SET USE_CACHED_RESULT = FALSE;


SELECT COUNT(*),SUM(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT_ID =50 
AND   JOB_ID='ST_CLERK'


SELECT COUNT(*),SUM(SALARY) FROM EMPLOYEES
WHERE SALARY >2000



CREATE OR REPLACE MATERIALIZED VIEW MV_EMPLOYEES_SALARY
CLUSTER BY (SALARY)
AS
SELECT
      EMPLOYEE_ID  ,
      FIRST_NAME   ,
      LAST_NAME    ,
      EMAIL        ,
      PHONE_NUMBER ,
      HIRE_DATE    ,
      JOB_ID       ,
      SALARY       ,
      COMMISSION_PCT, 
      MANAGER_ID   ,  
      DEPARTMENT_ID
FROM HRMS.HR.EMPLOYEES;

SELECT COUNT(*),SUM(SALARY) FROM MV_EMPLOYEES_SALARY 
WHERE SALARY >2000;



CREATE OR REPLACE MATERIALIZED VIEW MV_EMPLOYEES_EMAIL_PHONE
CLUSTER BY (EMAIL,PHONE_NUMBER)
AS
SELECT
      EMPLOYEE_ID  ,
      FIRST_NAME   ,
      LAST_NAME    ,
      EMAIL        ,
      PHONE_NUMBER ,
      HIRE_DATE    ,
      JOB_ID       ,
      SALARY       ,
      COMMISSION_PCT, 
      MANAGER_ID   ,  
      DEPARTMENT_ID
FROM HRMS.HR.EMPLOYEES


SELECT COUNT(*) FROM MV_EMPLOYEES_EMAIL_PHONE 
WHERE EMAIL LIKE '@GMAIL.COM' AND PHONE_NUMBER LIKE '847*'


    
