USE DATABASE HRMS;

USE SCHEMA HR;

DESCRIBE TABLE REGIONS
DESCRIBE TABLE LOCATIONS



SHOW TABLES


SELECT 
       E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,     
       D.DEPARTMENT_NAME   
FROM HRMS.HR.EMPLOYEES E, HRMS.HR.DEPARTMENTS D
WHERE E.DEPARTMENT_ID =D.DEPARTMENT_ID;




SELECT 
       E.EMPLOYEE_ID,
       E.FIRST_NAME,
       D.DEPARTMENT_NAME,  
       E.LAST_NAME     
    FROM HRMS.HR.EMPLOYEES E, HRMS.HR.DEPARTMENTS D
WHERE E.DEPARTMENT_ID =D.DEPARTMENT_ID


ALTER SESSION SET USE_CACHED_RESULT = FALSE;

ALTER ACCOUNT SET USE_CACHED_RESULT = FALSE;


SELECT COUNT(*) FROM HRMS.HR.EMPLOYEES 


ALTER SESSION SET USE_CACHED_RESULT = FALSE;

ALTER SESSION SET USE_CACHED_RESULT = TRUE;