CREATE OR REPLACE WAREHOUSE SCALE_LAB_WH
WITH 
WAREHOUSE_SIZE = 'XSMALL'  
AUTO_SUSPEND = 5
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE 
ENABLE_QUERY_ACCELERATION = TRUE
QUERY_ACCELERATION_MAX_SCALE_FACTOR = 2
COMMENT = 'Create Date :1-Jan-2099, 
           Created by: Sujith Nair,
           Use-Case:Snowflake QAS';


SHOW  WAREHOUSES LIKE 'SCALE_LAB_WH'


ALTER WAREHOUSE SCALE_LAB_WH SET QUERY_ACCELERATION_MAX_SCALE_FACTOR =5

SHOW  WAREHOUSES LIKE 'SCALE_LAB_WH'

ALTER WAREHOUSE SCALE_LAB_WH SET ENABLE_QUERY_ACCELERATION = FALSE;

SHOW  WAREHOUSES LIKE 'SCALE_LAB_WH'









ALTER WAREHOUSE SCALE_LAB_WH SET ENABLE_QUERY_ACCELERATION = TRUE;








USE DATABASE HRMS

