--Creating Users and Roles

USE ROLE ACCOUNTADMIN;

SELECT CURRENT_ROLE();


GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SECURITYADMIN;


USE ROLE SECURITYADMIN;


CREATE OR REPLACE USER USER_SUJITH
PASSWORD ='USER_SUJITH'
MUST_CHANGE_PASSWORD =FALSE
DEFAULT_ROLE =ACCOUNTADMIN;

ALTER USER USER_SUJITH SET DEFAULT_ROLE =PUBLIC;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO  USER USER_SUJITH;


--Creating Role ROLE_SNOWFLAKE_DBA which will be assigned to USER_SUJITH

CREATE OR REPLACE ROLE ROLE_SNOWFLAKE_DBA;


SHOW ROLES LIKE 'ROLE_SNOWFLAKE_DBA';

SHOW USERS;


GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_SNOWFLAKE_DBA;

GRANT USAGE ON DATABASE HRMS TO ROLE ROLE_SNOWFLAKE_DBA;
GRANT USAGE ON SCHEMA HRMS.HR TO ROLE ROLE_SNOWFLAKE_DBA;


GRANT CREATE TABLE ON SCHEMA  HRMS.HR TO ROLE ROLE_SNOWFLAKE_DBA;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA HRMS.HR TO ROLE ROLE_SNOWFLAKE_DBA;

GRANT ROLE ROLE_SNOWFLAKE_DBA TO USER USER_SUJITH;

SHOW GRANTS TO ROLE ROLE_SNOWFLAKE_DBA;


GRANT ROLE ACCOUNTADMIN TO ROLE ROLE_SNOWFLAKE_DBA;


REVOKE  ROLE ACCOUNTADMIN FROM ROLE ROLE_SNOWFLAKE_DBA;


--Creating Role ROLE_SNOWFLAKE_DA which will be assigned to USER_VIKRAM

CREATE OR REPLACE USER USER_VIKRAM
PASSWORD ='USER_VIKRAM'
MUST_CHANGE_PASSWORD =FALSE;


CREATE OR REPLACE ROLE ROLE_SNOWFLAKE_DA;

GRANT USAGE ON DATABASE HRMS  TO ROLE ROLE_SNOWFLAKE_DA;
GRANT USAGE ON SCHEMA HRMS.HR TO ROLE ROLE_SNOWFLAKE_DA;

GRANT CREATE TABLE ON SCHEMA HRMS.HR TO ROLE ROLE_SNOWFLAKE_DA;
GRANT SELECT ON ALL TABLES IN SCHEMA HRMS.HR TO ROLE ROLE_SNOWFLAKE_DA;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE_SNOWFLAKE_DA;

GRANT ROLE ROLE_SNOWFLAKE_DA TO USER USER_VIKRAM;

ALTER USER USER_VIKRAM SET DEFAULT_ROLE =ROLE_SNOWFLAKE_DA;
              


--Creating Role ROLE_SNOWFLAKE_DA which will be assigned to USER_RAHUL

CREATE OR REPLACE USER USER_RAHUL
PASSWORD ='USER_RAHUL'
MUST_CHANGE_PASSWORD =FALSE;


CREATE OR REPLACE ROLE ROLE_DATA_ENGINEER;

GRANT USAGE ON DATABASE HRMS  TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON SCHEMA HRMS.HR TO ROLE ROLE_DATA_ENGINEER;

GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA HRMS.HR TO ROLE ROLE_DATA_ENGINEER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE_DATA_ENGINEER;              

GRANT ROLE ROLE_DATA_ENGINEER TO USER USER_RAHUL;              

ALTER USER USER_RAHUL SET DEFAULT_ROLE =ROLE_DATA_ENGINEER;


--Creating Role ROLE_BI_DEVELOPER which will be assigned to USER_LEENA

CREATE OR REPLACE USER USER_LEENA
PASSWORD ='USER_LEENA'
MUST_CHANGE_PASSWORD =FALSE;



CREATE OR REPLACE ROLE ROLE_BI_DEVELOPER;

GRANT USAGE ON DATABASE HRMS  TO ROLE ROLE_BI_DEVELOPER;

GRANT USAGE ON SCHEMA HRMS.HR TO ROLE ROLE_BI_DEVELOPER;

GRANT SELECT ON ALL TABLES IN SCHEMA HRMS.HR TO ROLE ROLE_BI_DEVELOPER;
              
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE_BI_DEVELOPER;

GRANT ROLE ROLE_BI_DEVELOPER TO USER USER_LEENA;

ALTER USER USER_LEENA SET DEFAULT_ROLE =ROLE_BI_DEVELOPER;