
--ORGADMIN 

USE ROLE ORGADMIN;

SHOW ORGANIZATION ACCOUNTS;


SELECT * FROM SNOWFLAKE.ORGANIZATION_USAGE.METERING_DAILY_HISTORY;


USE ROLE ACCOUNTADMIN;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE ORGADMIN;

USE ROLE ORGADMIN;



SELECT * FROM SNOWFLAKE.ORGANIZATION_USAGE.METERING_DAILY_HISTORY;


ALTER ACCOUNT MKB58028 SET IS_ORG_ADMIN = TRUE;



REVOKE IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE FROM ROLE ORGADMIN;