
--DATABASE ROLES 

USE ROLE ACCOUNTADMIN;


SHOW ROLES LIKE '%ROLE_BI_DEVELOPER%'


GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER TO ROLE ROLE_BI_DEVELOPER;


GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE ROLE_DATA_ENGINEER;