USE DATABASE HRMS;

CREATE OR REPLACE SCHEMA SALES;  

-- Create the SALES table

CREATE OR REPLACE TABLE HRMS.SALES.DAILY_SALES 
(
    ID              INT, 
    PRODUCT         VARCHAR(50),
    QUANTITY        INT,
    PRICE           DECIMAL(10, 2),
    SALE_DATE       DATE,
    DEPARTMENT      NUMBER
);


-- Insert some sample data into the SALES table

INSERT INTO HRMS.SALES.DAILY_SALES (id, product, quantity, price, SALE_DATE ,DEPARTMENT)
VALUES (1, 'Laptop', 5, 1200.00, '2024-06-01',60),
       (2, 'iPhone', 2, 999.00, '2025-02-21',60);


SELECT * FROM HRMS.SALES.DAILY_SALES ;


CREATE OR REPLACE ROLE ROLE_SALES_DEVELOPER;

GRANT USAGE ON DATABASE HRMS  TO ROLE ROLE_SALES_DEVELOPER;
GRANT USAGE ON SCHEMA HRMS.SALES TO ROLE ROLE_SALES_DEVELOPER;
GRANT SELECT ON ALL TABLES IN SCHEMA HRMS.SALES TO ROLE ROLE_SALES_DEVELOPER;           
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE_SALES_DEVELOPER;

GRANT ROLE ROLE_SALES_DEVELOPER TO USER USER_RAHUL;


CREATE OR REPLACE SCHEMA HRMS.FINANCE;


-- Create the Finance table

CREATE OR REPLACE TABLE HRMS.FINANCE.PRODUCT_PROFIT_MARGIN 
(
    ID                       INT, 
    NET_PROFIT_MARGIN_PCT    DECIMAL (15,2),
    GROSS_PROFIT_PCT         DECIMAL (15,2),
    APPROX_PROFIT_AMT        DECIMAL (15,2)   
    
);


-- Insert some sample data into the SALES table

INSERT INTO HRMS.FINANCE.PRODUCT_PROFIT_MARGIN (id, NET_PROFIT_MARGIN_PCT, GROSS_PROFIT_PCT, APPROX_PROFIT_AMT)
VALUES (1,  20, 30, 300.00),
       (2,  30, 10, 400.00)
;


CREATE OR REPLACE ROLE ROLE_FINANCE_DEVELOPER;
GRANT USAGE ON DATABASE HRMS  TO ROLE ROLE_FINANCE_DEVELOPER;
GRANT USAGE ON SCHEMA HRMS.FINANCE TO ROLE ROLE_FINANCE_DEVELOPER;
GRANT SELECT ON ALL TABLES IN SCHEMA HRMS.FINANCE TO ROLE ROLE_FINANCE_DEVELOPER;
           
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE_FINANCE_DEVELOPER;

GRANT ROLE ROLE_FINANCE_DEVELOPER TO USER USER_RAHUL;


USE DATABASE HRMS;


USE ROLE ROLE_FINANCE_DEVELOPER;

SHOW SCHEMAS IN DATABASE HRMS;


USE ROLE ROLE_SALES_DEVELOPER;

SHOW SCHEMAS IN DATABASE HRMS;

SELECT * FROM HRMS.SALES.DAILY_SALES;

SELECT * FROM HRMS.FINANCE.PRODUCT_PROFIT_MARGIN


SELECT DS.*,FD.* FROM HRMS.SALES.DAILY_SALES DS INNER JOIN 
              HRMS.FINANCE.PRODUCT_PROFIT_MARGIN PPM
ON DS.ID=PPM.ID


SELECT CURRENT_SECONDARY_ROLES()

USE SECONDARY ROLES  ALL;