
SHOW ROLES LIKE 'ROLE_%'


SHOW GRANTS TO ROLE ROLE_BI_DEVELOPER;
SHOW GRANTS TO ROLE ROLE_DATA_ENGINEER;
SHOW GRANTS TO ROLE ROLE_SNOWFLAKE_DA;
SHOW GRANTS TO ROLE ROLE_SNOWFLAKE_DBA;


USE ROLE ACCOUNTADMIN;

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES
WHERE GRANTED_TO='ROLE' 
AND GRANTEE_NAME LIKE 'ROLE_BI_DEVELOPER'
ORDER BY 4

USE ROLE SECURITYADMIN;


--Creating a role Hirerchy 

GRANT ROLE ROLE_BI_DEVELOPER TO ROLE ROLE_DATA_ENGINEER;

GRANT ROLE ROLE_DATA_ENGINEER TO ROLE ROLE_SNOWFLAKE_DA;

GRANT ROLE ROLE_SNOWFLAKE_DA TO ROLE ROLE_SNOWFLAKE_DBA;




GRANT ROLE SECURITYADMIN TO ROLE SYSADMIN;