HRMS.HR.REGIONS--Streams

USE DATABASE HRMS;

CREATE OR REPLACE SCHEMA CDC;

CREATE OR REPLACE TABLE CDC.EMPLOYEES
(
EMPLOYEE_ID        NUMBER(6,0),
FIRST_NAME         VARCHAR(20),
LAST_NAME          VARCHAR(25),
EMAIL              VARCHAR(25),
PHONE_NUMBER       VARCHAR(20),
HIRE_DATE          DATE,
JOB_ID             VARCHAR(10),
SALARY             NUMBER(8,2),
COMMISSION_PCT     NUMBER(2,2),
MANAGER_ID         NUMBER(6,0),
DEPARTMENT_ID      NUMBER(4,0)
);


INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 100, 'STEVEN', 'KING', 'SKING', '515.123.4567', TO_DATE('17-06-2003', 'DD-MM-YYYY'), 'AD_PRES', 24000, NULL, NULL, 90);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 101, 'NEENA', 'KOCHHAR', 'NKOCHHAR', '515.123.4568', TO_DATE('21-09-2005', 'DD-MM-YYYY'), 'AD_VP', 17000, NULL, 100, 90);


SELECT * FROM EMPLOYEES;


CREATE OR REPLACE TABLE EMPLOYEES_DIM_CDC
(
EMPLOYEE_ID        NUMBER(6,0),
FIRST_NAME         VARCHAR(20),
LAST_NAME          VARCHAR(25),
EMAIL              VARCHAR(25),
PHONE_NUMBER       VARCHAR(20),
HIRE_DATE          DATE,
JOB_ID             VARCHAR(10),
SALARY             NUMBER(8,2),
COMMISSION_PCT     NUMBER(2,2),
MANAGER_ID         NUMBER(6,0),
DEPARTMENT_ID      NUMBER(4,0),
LAST_UPDATED_TS    TIMESTAMP ,
LAST_INSERTED_TS   TIMESTAMP 
);


CREATE OR REPLACE STREAM STREAM_EMPLOYEES ON TABLE CDC.EMPLOYEES; 

SELECT * FROM STREAM_EMPLOYEES;

SELECT * FROM CDC.EMPLOYEES;

UPDATE CDC.EMPLOYEES
SET SALARY=21000
WHERE EMPLOYEE_ID =100;


UPDATE CDC.EMPLOYEES
SET SALARY=18000
WHERE EMPLOYEE_ID =101;


SELECT * FROM CDC.EMPLOYEES;


SELECT * FROM STREAM_EMPLOYEES ORDER BY 1;

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 102, 'LEX', 'DE HAAN', 'LDEHAAN', '515.123.4569', TO_DATE('13-01-2001', 'DD-MM-YYYY'), 'AD_VP', 17000, NULL, 100, 90);


SELECT * FROM CDC.EMPLOYEES;

SELECT * FROM STREAM_EMPLOYEES ORDER BY 1;


MERGE INTO EMPLOYEES_DIM_CDC EDIM
USING STREAM_EMPLOYEES CDC
ON EDIM.EMPLOYEE_ID = CDC.EMPLOYEE_ID 
WHEN MATCHED AND 
     METADATA$ACTION = 'INSERT' AND 
     METADATA$ISUPDATE = TRUE
THEN UPDATE
        SET 
        EDIM.EMPLOYEE_ID     = CDC.EMPLOYEE_ID,
        EDIM.FIRST_NAME      = CDC.FIRST_NAME,
        EDIM.LAST_NAME       = CDC.LAST_NAME,
        EDIM.EMAIL           = CDC.EMAIL,  
        EDIM.PHONE_NUMBER    = CDC.PHONE_NUMBER,
        EDIM.HIRE_DATE       = CDC.HIRE_DATE,
        EDIM.JOB_ID          = CDC.JOB_ID,  
        EDIM.SALARY          = CDC.SALARY,
        EDIM.COMMISSION_PCT  = CDC.COMMISSION_PCT,
        EDIM.MANAGER_ID      = CDC.MANAGER_ID, 
        EDIM.DEPARTMENT_ID   = CDC.DEPARTMENT_ID,
        EDIM.LAST_UPDATED_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND
         METADATA$ACTION = 'INSERT' 
THEN INSERT 
(EDIM.EMPLOYEE_ID,EDIM.FIRST_NAME, EDIM.LAST_NAME, EDIM.EMAIL, EDIM.PHONE_NUMBER,      
                                                                    EDIM.HIRE_DATE,EDIM.JOB_ID,EDIM.SALARY,EDIM.COMMISSION_PCT,EDIM.MANAGER_ID,EDIM.DEPARTMENT_ID,EDIM.LAST_UPDATED_TS,EDIM.LAST_INSERTED_TS)
VALUES
(CDC.EMPLOYEE_ID,CDC.FIRST_NAME, CDC.LAST_NAME, CDC.EMAIL, CDC.PHONE_NUMBER, CDC.HIRE_DATE,CDC.JOB_ID, CDC.SALARY,CDC.COMMISSION_PCT,CDC.MANAGER_ID,CDC.DEPARTMENT_ID,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


SELECT * FROM EMPLOYEES_DIM_CDC;


SELECT * FROM STREAM_EMPLOYEES;


SELECT * FROM CDC.EMPLOYEES;


DELETE FROM CDC.EMPLOYEES
WHERE EMPLOYEE_ID =100;


SELECT * FROM STREAM_EMPLOYEES ORDER BY 1;

UPDATE  CDC.EMPLOYEES
SET  SALARY=24000,
     JOB_ID='AD_PRES'
WHERE EMPLOYEE_ID=101;

SELECT * FROM CDC.EMPLOYEES;


SELECT * FROM STREAM_EMPLOYEES ORDER BY 1;


MERGE INTO EMPLOYEES_DIM_CDC EDIM
USING STREAM_EMPLOYEES CDC
ON EDIM.EMPLOYEE_ID = CDC.EMPLOYEE_ID 
WHEN MATCHED AND 
     METADATA$ACTION = 'INSERT' AND 
     METADATA$ISUPDATE = TRUE
THEN UPDATE
        SET 
        EDIM.EMPLOYEE_ID     = CDC.EMPLOYEE_ID,
        EDIM.FIRST_NAME      = CDC.FIRST_NAME,
        EDIM.LAST_NAME       = CDC.LAST_NAME,
        EDIM.EMAIL           = CDC.EMAIL,  
        EDIM.PHONE_NUMBER    = CDC.PHONE_NUMBER,
        EDIM.HIRE_DATE       = CDC.HIRE_DATE,
        EDIM.JOB_ID          = CDC.JOB_ID,  
        EDIM.SALARY          = CDC.SALARY,
        EDIM.COMMISSION_PCT  = CDC.COMMISSION_PCT,
        EDIM.MANAGER_ID      = CDC.MANAGER_ID, 
        EDIM.DEPARTMENT_ID   = CDC.DEPARTMENT_ID,
        EDIM.LAST_UPDATED_TS = CURRENT_TIMESTAMP()
WHEN  MATCHED AND METADATA$ACTION ='DELETE'
              AND METADATA$ISUPDATE = FALSE      
THEN DELETE        

WHEN NOT MATCHED AND 
     METADATA$ACTION = 'INSERT' AND 
     METADATA$ISUPDATE = FALSE           
THEN INSERT 
(EDIM.EMPLOYEE_ID,EDIM.FIRST_NAME, EDIM.LAST_NAME, EDIM.EMAIL, EDIM.PHONE_NUMBER,      
                                                                    EDIM.HIRE_DATE,EDIM.JOB_ID,EDIM.SALARY,EDIM.COMMISSION_PCT,EDIM.MANAGER_ID,EDIM.DEPARTMENT_ID,EDIM.LAST_UPDATED_TS,EDIM.LAST_INSERTED_TS)
VALUES
(CDC.EMPLOYEE_ID,CDC.FIRST_NAME, CDC.LAST_NAME, CDC.EMAIL, CDC.PHONE_NUMBER, CDC.HIRE_DATE,CDC.JOB_ID, CDC.SALARY,CDC.COMMISSION_PCT,CDC.MANAGER_ID,CDC.DEPARTMENT_ID,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);



SELECT * FROM EMPLOYEES_DIM_CDC ORDER BY 1;


SELECT * FROM EMPLOYEES_DIM_CDC;


--Task and Streams.

SELECT SYSTEM$STREAM_HAS_DATA('STREAM_EMPLOYEES');

SELECT * FROM CDC.EMPLOYEES;

UPDATE CDC.EMPLOYEES
SET PHONE_NUMBER ='000.000.0000'
WHERE EMPLOYEE_ID = 102;


CREATE OR REPLACE TASK TASK_UPDATE_EMPLOYEES_DIM_CDC
WAREHOUSE = COMPUTE_WH 
SCHEDULE = '10 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STREAM_EMPLOYEES')
AS
MERGE INTO EMPLOYEES_DIM_CDC EDIM
USING STREAM_EMPLOYEES CDC
ON EDIM.EMPLOYEE_ID = CDC.EMPLOYEE_ID 
WHEN MATCHED AND 
     METADATA$ACTION = 'INSERT' AND 
     METADATA$ISUPDATE = TRUE
THEN UPDATE
        SET 
        EDIM.EMPLOYEE_ID     = CDC.EMPLOYEE_ID,
        EDIM.FIRST_NAME      = CDC.FIRST_NAME,
        EDIM.LAST_NAME       = CDC.LAST_NAME,
        EDIM.EMAIL           = CDC.EMAIL,  
        EDIM.PHONE_NUMBER    = CDC.PHONE_NUMBER,
        EDIM.HIRE_DATE       = CDC.HIRE_DATE,
        EDIM.JOB_ID          = CDC.JOB_ID,  
        EDIM.SALARY          = CDC.SALARY,
        EDIM.COMMISSION_PCT  = CDC.COMMISSION_PCT,
        EDIM.MANAGER_ID      = CDC.MANAGER_ID, 
        EDIM.DEPARTMENT_ID   = CDC.DEPARTMENT_ID,
        EDIM.LAST_UPDATED_TS = CURRENT_TIMESTAMP()
WHEN  MATCHED AND METADATA$ACTION ='DELETE'
              AND METADATA$ISUPDATE = FALSE      
THEN DELETE        
WHEN NOT MATCHED AND 
     METADATA$ACTION = 'INSERT' AND 
     METADATA$ISUPDATE = FALSE           
THEN INSERT 
(EDIM.EMPLOYEE_ID,EDIM.FIRST_NAME, EDIM.LAST_NAME, EDIM.EMAIL, EDIM.PHONE_NUMBER,      
                                                                    EDIM.HIRE_DATE,EDIM.JOB_ID,EDIM.SALARY,EDIM.COMMISSION_PCT,EDIM.MANAGER_ID,EDIM.DEPARTMENT_ID,EDIM.LAST_UPDATED_TS,EDIM.LAST_INSERTED_TS)
VALUES
(CDC.EMPLOYEE_ID,CDC.FIRST_NAME, CDC.LAST_NAME, CDC.EMAIL, CDC.PHONE_NUMBER, CDC.HIRE_DATE,CDC.JOB_ID, CDC.SALARY,CDC.COMMISSION_PCT,CDC.MANAGER_ID,CDC.DEPARTMENT_ID,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

ALTER TASK TASK_UPDATE_EMPLOYEES_DIM_CDC  RESUME;

EXECUTE TASK TASK_UPDATE_EMPLOYEES_DIM_CDC;

SELECT * FROM CDC.EMPLOYEES_DIM_CDC ORDER BY 1;

SELECT * FROM CDC.EMPLOYEES;


INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 103, 'ALEXANDER', 'HUNOLD', 'AHUNOLD', '590.423.4567', TO_DATE('03-01-2006', 'DD-MM-YYYY'), 'IT_PROG', 9000, NULL, 102, 60);


SELECT SYSTEM$STREAM_HAS_DATA('STREAM_EMPLOYEES')


SELECT * FROM STREAM_EMPLOYEES ORDER BY 1;


EXECUTE TASK TASK_UPDATE_EMPLOYEES_DIM_CDC;  


SELECT * FROM CDC.EMPLOYEES_DIM_CDC ORDER BY 1;

-- Using more than 1 table in a Merge.

CREATE TABLE CDC.DEPARTMENTS 
AS
SELECT * FROM HR.DEPARTMENTS;

SELECT * FROM CDC.DEPARTMENTS;

CREATE OR REPLACE TABLE EMP_DEPT_DIM_CDC
(
EMPLOYEE_ID        NUMBER(6,0),
FIRST_NAME         VARCHAR(20),
LAST_NAME          VARCHAR(25),
EMAIL              VARCHAR(25),
PHONE_NUMBER       VARCHAR(20),
HIRE_DATE          DATE,
JOB_ID             VARCHAR(10),
SALARY             NUMBER(8,2),
COMMISSION_PCT     NUMBER(2,2),
MANAGER_ID         NUMBER(6,0),
DEPARTMENT_ID      NUMBER(4,0),
DEPARTMENT_NAME    VARCHAR(10),
LAST_UPDATED_TS    TIMESTAMP ,
LAST_INSERTED_TS   TIMESTAMP 
);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 104, 'BRUCE', 'ERNST', 'BERNST', '590.423.4568', TO_DATE('21-05-2007', 'DD-MM-YYYY'), 'IT_PROG', 6000, NULL, 103, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 105, 'DAVID', 'AUSTIN', 'DAUSTIN', '590.423.4569', TO_DATE('25-06-2005', 'DD-MM-YYYY'), 'IT_PROG', 4800, NULL, 103, 60);


SELECT * FROM STREAM_EMPLOYEES;


MERGE INTO EMP_DEPT_DIM_CDC EDIM
USING (
        SELECT SED.*,D.DEPARTMENT_NAME FROM STREAM_EMPLOYEES  SED
               JOIN CDC.DEPARTMENTS D
               ON SED.DEPARTMENT_ID=D.DEPARTMENT_ID
      ) CDC
ON EDIM.EMPLOYEE_ID = CDC.EMPLOYEE_ID 
WHEN MATCHED AND 
     METADATA$ACTION = 'INSERT' AND 
     METADATA$ISUPDATE = TRUE
THEN UPDATE
        SET 
        EDIM.EMPLOYEE_ID     = CDC.EMPLOYEE_ID,
        EDIM.FIRST_NAME      = CDC.FIRST_NAME,
        EDIM.LAST_NAME       = CDC.LAST_NAME,
        EDIM.EMAIL           = CDC.EMAIL,  
        EDIM.PHONE_NUMBER    = CDC.PHONE_NUMBER,
        EDIM.HIRE_DATE       = CDC.HIRE_DATE,
        EDIM.JOB_ID          = CDC.JOB_ID,  
        EDIM.SALARY          = CDC.SALARY,
        EDIM.COMMISSION_PCT  = CDC.COMMISSION_PCT,
        EDIM.MANAGER_ID      = CDC.MANAGER_ID, 
        EDIM.DEPARTMENT_ID   = CDC.DEPARTMENT_ID,
        EDIM.DEPARTMENT_NAME = CDC.DEPARTMENT_NAME,
        EDIM.LAST_UPDATED_TS = CURRENT_TIMESTAMP()
WHEN  MATCHED AND METADATA$ACTION ='DELETE'
              AND METADATA$ISUPDATE = FALSE      
THEN DELETE        
WHEN NOT MATCHED AND 
     METADATA$ACTION = 'INSERT' AND 
     METADATA$ISUPDATE = FALSE           
THEN INSERT 
(EDIM.EMPLOYEE_ID,EDIM.FIRST_NAME, EDIM.LAST_NAME, EDIM.EMAIL, EDIM.PHONE_NUMBER,                                                                   
                                            EDIM.HIRE_DATE,EDIM.JOB_ID,EDIM.SALARY,EDIM.COMMISSION_PCT,EDIM.MANAGER_ID,EDIM.DEPARTMENT_ID,EDIM.DEPARTMENT_NAME,EDIM.LAST_UPDATED_TS,EDIM.LAST_INSERTED_TS)
VALUES
(CDC.EMPLOYEE_ID,CDC.FIRST_NAME, CDC.LAST_NAME, CDC.EMAIL, CDC.PHONE_NUMBER, CDC.HIRE_DATE,CDC.JOB_ID, CDC.SALARY,CDC.COMMISSION_PCT,CDC.MANAGER_ID,CDC.DEPARTMENT_ID,CDC.DEPARTMENT_NAME,
                                                                                                                                                                    CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

SELECT * FROM EMP_DEPT_DIM_CDC;


--Creating a stream on a view

CREATE OR REPLACE TABLE CDC.LOCATIONS
AS 
SELECT * FROM HR.LOCATIONS;

SELECT * FROM CDC.LOCATIONS;

CREATE OR REPLACE VIEW VIEW_EMP_DEPT_LOC
AS 
SELECT 
      E.*,
      D.DEPARTMENT_NAME,
      L.CITY
FROM 
     CDC.EMPLOYEES E, 
     CDC.DEPARTMENTS D,
     CDC.LOCATIONS L
WHERE E.DEPARTMENT_ID =D.DEPARTMENT_ID
AND L.LOCATION_ID=D.LOCATION_ID


CREATE OR REPLACE STREAM STREAM_VIEW_EMP_DEPT_LOC ON VIEW VIEW_EMP_DEPT_LOC;


INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 106, 'VALLI', 'PATABALLA', 'VPATABAL', '590.423.4560', TO_DATE('05-02-2006', 'DD-MM-YYYY'), 'IT_PROG', 4800, NULL, 103, 60);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 107, 'DIANA', 'LORENTZ', 'DLORENTZ', '590.423.5567', TO_DATE('07-02-2007', 'DD-MM-YYYY'), 'IT_PROG', 4200, NULL, 103, 60);


SELECT * FROM STREAM_VIEW_EMP_DEPT_LOC ORDER BY 1;


CREATE OR REPLACE TABLE EMP_DEPT_LOC_DIM_CDC
(
EMPLOYEE_ID        NUMBER(6,0),
FIRST_NAME         VARCHAR(20),
LAST_NAME          VARCHAR(25),
EMAIL              VARCHAR(25),
PHONE_NUMBER       VARCHAR(20),
HIRE_DATE          DATE,
JOB_ID             VARCHAR(10),
SALARY             NUMBER(8,2),
COMMISSION_PCT     NUMBER(2,2),
MANAGER_ID         NUMBER(6,0),
DEPARTMENT_ID      NUMBER(4,0),
DEPARTMENT_NAME    VARCHAR(10),
CITY               VARCHAR(10), 
LAST_UPDATED_TS    TIMESTAMP ,
LAST_INSERTED_TS   TIMESTAMP 
);


MERGE INTO EMP_DEPT_LOC_DIM_CDC EDIM
USING  STREAM_VIEW_EMP_DEPT_LOC  CDC
ON EDIM.EMPLOYEE_ID = CDC.EMPLOYEE_ID 
WHEN MATCHED AND 
     METADATA$ACTION = 'INSERT' AND 
     METADATA$ISUPDATE = TRUE
THEN UPDATE
        SET 
        EDIM.EMPLOYEE_ID     = CDC.EMPLOYEE_ID,
        EDIM.FIRST_NAME      = CDC.FIRST_NAME,
        EDIM.LAST_NAME       = CDC.LAST_NAME,
        EDIM.EMAIL           = CDC.EMAIL,  
        EDIM.PHONE_NUMBER    = CDC.PHONE_NUMBER,
        EDIM.HIRE_DATE       = CDC.HIRE_DATE,
        EDIM.JOB_ID          = CDC.JOB_ID,  
        EDIM.SALARY          = CDC.SALARY,
        EDIM.COMMISSION_PCT  = CDC.COMMISSION_PCT,
        EDIM.MANAGER_ID      = CDC.MANAGER_ID, 
        EDIM.DEPARTMENT_ID   = CDC.DEPARTMENT_ID,
        EDIM.DEPARTMENT_NAME = CDC.DEPARTMENT_NAME,
        EDIM.CITY            = CDC.CITY,
        EDIM.LAST_UPDATED_TS = CURRENT_TIMESTAMP()
WHEN  MATCHED AND METADATA$ACTION ='DELETE'
              AND METADATA$ISUPDATE = FALSE      
THEN DELETE        
WHEN NOT MATCHED AND 
     METADATA$ACTION = 'INSERT' AND 
     METADATA$ISUPDATE = FALSE           
THEN INSERT 
(EDIM.EMPLOYEE_ID,EDIM.FIRST_NAME, EDIM.LAST_NAME, EDIM.EMAIL, EDIM.PHONE_NUMBER,                                                                                                               EDIM.HIRE_DATE,EDIM.JOB_ID,EDIM.SALARY,EDIM.COMMISSION_PCT,EDIM.MANAGER_ID,EDIM.DEPARTMENT_ID,EDIM.DEPARTMENT_NAME,EDIM.CITY,EDIM.LAST_UPDATED_TS,EDIM.LAST_INSERTED_TS)
VALUES
(CDC.EMPLOYEE_ID,CDC.FIRST_NAME, CDC.LAST_NAME, CDC.EMAIL, CDC.PHONE_NUMBER, CDC.HIRE_DATE,CDC.JOB_ID, CDC.SALARY,CDC.COMMISSION_PCT,CDC.MANAGER_ID,CDC.DEPARTMENT_ID,CDC.DEPARTMENT_NAME,CDC.CITY,
                                                                                                                                                                    CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
                                                                                                                                                                                                               SELECT * FROM EMP_DEPT_LOC_DIM_CDC       
                                                                                                                                                                                                               
                                                                                                                                                                                                               
--Append only Stream

DROP TABLE CDC.EMPLOYEES ;

CREATE OR REPLACE TABLE CDC.EMPLOYEES
(
EMPLOYEE_ID        NUMBER(6,0),
FIRST_NAME         VARCHAR(20),
LAST_NAME          VARCHAR(25),
EMAIL              VARCHAR(25),
PHONE_NUMBER       VARCHAR(20),
HIRE_DATE          DATE,
JOB_ID             VARCHAR(10),
SALARY             NUMBER(8,2),
COMMISSION_PCT     NUMBER(2,2),
MANAGER_ID         NUMBER(6,0),
DEPARTMENT_ID      NUMBER(4,0)
);

CREATE OR REPLACE STREAM STREAM_EMPLOYEES_INSERT 
ON TABLE CDC.EMPLOYEES
APPEND_ONLY = TRUE 


SELECT * FROM STREAM_EMPLOYEES_INSERT;

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 114, 'DEN', 'RAPHAELY', 'DRAPHEAL', '515.127.4561', TO_DATE('07-12-2002', 'DD-MM-YYYY'), 'PU_MAN', 11000, NULL, 100, 30);


SELECT * FROM STREAM_EMPLOYEES_INSERT;


CREATE OR REPLACE TABLE CONSUME_THE_STREAM_INSERT
AS
SELECT * FROM STREAM_EMPLOYEES_INSERT;

SELECT * FROM STREAM_EMPLOYEES_INSERT;

SELECT * FROM CONSUME_THE_STREAM_INSERT;


UPDATE CDC.EMPLOYEES
SET SALARY =21000
WHERE EMPLOYEE_ID =114


SELECT * FROM STREAM_EMPLOYEES_INSERT;


--How to Empty a stream

SELECT * FROM EMPLOYEES;

CREATE OR REPLACE STREAM STREAM_EMPLOYEES ON TABLE CDC.EMPLOYEES; 

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 108, 'NANCY', 'GREENBERG', 'NGREENBE', '515.124.4569', TO_DATE('17-08-2002', 'DD-MM-YYYY'), 'FI_MGR', 12008, NULL, 101, 100);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 109, 'DANIEL', 'FAVIET', 'DFAVIET', '515.124.4169', TO_DATE('16-08-2002', 'DD-MM-YYYY'), 'FI_ACCOUNT', 9000, NULL, 108, 100);


SELECT * FROM STREAM_EMPLOYEES;


CREATE OR REPLACE STREAM STREAM_EMPLOYEES ON TABLE CDC.EMPLOYEES;


TRUNCATE STREAM STREAM_EMPLOYEES;


--Changes Clause

ALTER TABLE CDC.EMPLOYEES SET CHANGE_TRACKING = TRUE;

SELECT * FROM CDC.EMPLOYEES;

SET TS1 = (SELECT CURRENT_TIMESTAMP());  -- Initialize a session variable for the current timestamp.

SHOW VARIABLES LIKE 'TS1' 
 

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 111, 'ISMAEL', 'SCIARRA', 'ISCIARRA', '515.124.4369', TO_DATE('30-09-2005', 'DD-MM-YYYY'), 'FI_ACCOUNT', 7700, NULL, 108, 100);


INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 112, 'JOSE MANUEL', 'URMAN', 'JMURMAN', '515.124.4469', TO_DATE('07-03-2006', 'DD-MM-YYYY'), 'FI_ACCOUNT', 7800, NULL, 108, 100);

SET TS2 = (SELECT CURRENT_TIMESTAMP());

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 113, 'LUIS', 'POPP', 'LPOPP', '515.124.4567', TO_DATE('07-12-2007', 'DD-MM-YYYY'), 'FI_ACCOUNT', 6900, NULL, 108, 100);


SET TS3 = (SELECT CURRENT_TIMESTAMP());


SELECT * FROM CDC.EMPLOYEES
   CHANGES(INFORMATION => DEFAULT)
   AT(TIMESTAMP => $TS1)
  END(TIMESTAMP => $TS2);

SELECT * FROM EMPLOYEES
   CHANGES(INFORMATION => DEFAULT)
   AT(TIMESTAMP => $TS1)
  END(TIMESTAMP => $TS3);


UPDATE EMPLOYEES 
SET PHONE_NUMBER = '999.999.9999' 
WHERE EMPLOYEE_ID = 113;

SET TS4 = (SELECT CURRENT_TIMESTAMP());

SELECT * FROM EMPLOYEES
  CHANGES(INFORMATION => DEFAULT)
  AT(TIMESTAMP => $TS1)
  END(TIMESTAMP => $TS3);

 SELECT * FROM EMPLOYEES
  CHANGES(INFORMATION => DEFAULT)
  AT(TIMESTAMP => $TS1)
  END(TIMESTAMP => $TS4);

 
 DELETE FROM EMPLOYEES 
 WHERE EMPLOYEE_ID = 112;


 SET TS5 = (SELECT CURRENT_TIMESTAMP());


 SELECT * FROM EMPLOYEES
   CHANGES(INFORMATION => DEFAULT)
   AT(TIMESTAMP => $TS1)
   END(TIMESTAMP => $TS4);


SELECT * FROM EMPLOYEES
   CHANGES(INFORMATION => DEFAULT)
   AT(TIMESTAMP => $TS1)
   END(TIMESTAMP => $TS5);

SELECT * FROM EMPLOYEES
   CHANGES(INFORMATION => DEFAULT)
   AT(TIMESTAMP => $TS1)


CREATE OR REPLACE TABLE CONSUME_THE_CHANGES_TRACKING
AS
SELECT * FROM EMPLOYEES
   CHANGES(INFORMATION => DEFAULT)
   AT(TIMESTAMP => $TS1)

SELECT * FROM  CONSUME_THE_CHANGES_TRACKING;  

SELECT * FROM EMPLOYEES
   CHANGES(INFORMATION => DEFAULT)
   AT(TIMESTAMP => $TS1)



















----

SHOW TASKS;

CREATE OR REPLACE STREAM STREAM_EMPLOYEES ON TABLE CDC.EMPLOYEES;

SELECT * FROM STREAM_EMPLOYEES;


SELECT * FROM CDC.EMPLOYEES;



DROP STREAM STREAM_EMPLOYEES

DROP TABLE EMPLOYEES;