CREATE OR REPLACE DATABASE ICEBERG;

CREATE OR REPLACE SCHEMA HR;


CREATE OR REPLACE EXTERNAL VOLUME ICEBERG_VOLUME
STORAGE_LOCATIONS =
(
    (
       NAME ='US-EAST-1' 
       STORAGE_PROVIDER ='s3'
       STORAGE_AWS_ROLE_ARN ='arn:aws:iam::133202620729:role/s3_glue_Role'
       STORAGE_BASE_URL  ='s3://learn2cloud-snowflake/external_table/csv/'
    
    )
);

DESC VOLUME  ICEBERG_VOLUME

CREATE OR REPLACE CATALOG INTEGRATION CAT_INT_GLUE
CATALOG_SOURCE = GLUE
CATALOG_NAMESPACE ='hrms'
TABLE_FORMAT = ICEBERG
GLUE_AWS_ROLE_ARN ='arn:aws:iam::133202620729:role/s3_glue_Role'
GLUE_CATALOG_ID='133202620729'
GLUE_REGION='us-east-1'
ENABLED=TRUE;

SHOW INTEGRATIONS;

DESCRIBE INTEGRATION CAT_INT_GLUE

CREATE OR REPLACE ICEBERG TABLE ICEBERG.HR.IB_EMPLOYEES
CATALOG_TABLE_NAME ='aws_iceberg_employees'
CATALOG ='cat_int_glue'
EXTERNAL_VOLUME = 'iceberg_volume';
--METADATA_FILE_PATH =


SELECT * FROM ICEBERG.HR.IB_EMPLOYEES;


UPDATE ICEBERG.HR.IB_EMPLOYEES
SET FIRST_NAME ='TEST'
WHERE EMPLOYEE_ID =108;


ALTER ICEBERG TABLE ICEBERG.HR.IB_EMPLOYEES CONVERT TO MANAGED
BASE_LOCATION ='ib_employees-managed-table'


CREATE OR REPLACE CATALOG INTEGRATION CAT_INT_SNOWFLAKE
CATALOG_SOURCE = OBJECT_STORE
TABLE_FORMAT = ICEBERG
ENABLED=TRUE;


SHOW TABLES


SELECT MIN(FIRST_NAME),MAX(FIRST_NAME),MIN(LAST_NAME),MAX(LAST_NAME), MIN(EMAIL), MAX(EMAIL),
MIN(PHONE_NUMBER), MAX(PHONE_NUMBER),
MIN(HIRE_DATE), MAX(HIRE_DATE)
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (118,107,119,113)