CREATE OR REPLACE DATABASE ICEBERG;


CREATE OR REPLACE SCHEMA HR;


CREATE OR REPLACE EXTERNAL VOLUME ICEBERG_VOLUME_UNMANAGED
STORAGE_LOCATIONS =
(
    (
       NAME ='HR Data ' 
       STORAGE_PROVIDER ='s3'
       STORAGE_AWS_ROLE_ARN ='arn:aws:iam::133202620729:role/SNOWFLAKE_GLUE_ADMIN_ROLE'
       STORAGE_BASE_URL  ='s3://learn2cloud-iceberg/employees_iceberg/'
    
    )
);


SHOW EXTERNAL VOLUMES;


DESCRIBE EXTERNAL VOLUME ICEBERG_VOLUME_UNMANAGED;


DROP EXTERNAL VOLUME ICEBERG_VOLUME_UNMANAGED;


CREATE OR REPLACE CATALOG INTEGRATION CAT_INT_GLUE_UNMANAGED
TABLE_FORMAT = ICEBERG
CATALOG_SOURCE = GLUE
GLUE_REGION='us-west-2'
CATALOG_NAMESPACE ='hrms'
GLUE_AWS_ROLE_ARN ='arn:aws:iam::133202620729:role/SNOWFLAKE_GLUE_ADMIN_ROLE'
GLUE_CATALOG_ID='133202620729'
ENABLED=TRUE;

SHOW INTEGRATIONS;

SHOW CATALOG INTEGRATIONS;

DESCRIBE INTEGRATION CAT_INT_GLUE_UNMANAGED;

DROP INTEGRATION CAT_INT_GLUE_UNMANAGED;

SHOW ICEBERG TABLES;

CREATE OR REPLACE ICEBERG TABLE ICEBERG.HR.UNMANAGED_IB_EMPLOYEES
CATALOG_TABLE_NAME ='aws_iceberg_employees'
CATALOG ='CAT_INT_GLUE_UNMANAGED'
EXTERNAL_VOLUME = 'ICEBERG_VOLUME_UNMANAGED';


DROP TABLE ICEBERG.HR.UNMANAGED_IB_EMPLOYEES;


SELECT * FROM ICEBERG.HR.UNMANAGED_IB_EMPLOYEES;


SELECT COUNT(*) FROM ICEBERG.HR.UNMANAGED_IB_EMPLOYEES;


ALTER ICEBERG TABLE ICEBERG.HR.UNMANAGED_IB_EMPLOYEES REFRESH ;


SELECT * FROM ICEBERG.HR.UNMANAGED_IB_EMPLOYEES WHERE EMPLOYEE_ID=104;



SELECT COUNT(*) FROM ICEBERG.HR.UNMANAGED_IB_EMPLOYEES;

UPDATE ICEBERG.HR.UNMANAGED_IB_EMPLOYEES
SET JOB_ID ='AD_PRES'
WHERE EMPLOYEE_ID =101;