USE DATABASE ICEBERG;


USE SCHEMA HR;



CREATE OR REPLACE EXTERNAL VOLUME ICEBERG_VOLUME_MANAGED
STORAGE_LOCATIONS =
(
    (
       NAME ='HR Data' 
       STORAGE_PROVIDER ='s3'
       STORAGE_AWS_ROLE_ARN ='arn:aws:iam::133202620729:role/SNOWFLAKE_GLUE_ADMIN_ROLE'
       STORAGE_BASE_URL  ='s3://learn2cloud-iceberg/employees_iceberg_managed/'
    
    )
);



CREATE ICEBERG TABLE MANAGED_IB_EMPLOYEES (
  EMPLOYEE_ID    STRING,
  FIRST_NAME     STRING,
  LAST_NAME      STRING ,
  EMAIL          STRING,
  PHONE_NUMBER   STRING,
  HIRE_DATE      STRING ,
  JOB_ID         STRING ,
  SALARY         STRING,
  COMMISSION_PCT STRING,
  MANAGER_ID     STRING,
  DEPARTMENT_ID  STRING
)
CATALOG = 'SNOWFLAKE'
EXTERNAL_VOLUME ='ICEBERG_VOLUME_MANAGED'
BASE_LOCATION = 'MANAGED_IB_EMPLOYEES';


SELECT * FROM MANAGED_IB_EMPLOYEES;

INSERT INTO MANAGED_IB_EMPLOYEES 
SELECT * FROM HRMS.HR.EMPLOYEES;

UPDATE MANAGED_IB_EMPLOYEES
SET JOB_ID ='AD_PRES'
WHERE EMPLOYEE_ID =101;



ALTER ICEBERG TABLE ICEBERG.HR.UNMANAGED_IB_EMPLOYEES 
CONVERT TO MANAGED 
BASE_LOCATION = 'UNMANAGED_2_MANAGED_IB_EMPLOYEES';