SHOW SHARES

DESC SHARE VMQFECX.MKB58028.SHARE_HRMS_HR  

CREATE OR REPLACE DATABASE INBOUND_SHARE_HRMSDB FROM SHARE VMQFECX.MKB58028.SHARE_HRMS_HR

DESCRIBE DATABASE INBOUND_SHARE_HRMSDB

SELECT * FROM INBOUND_SHARE_HRMSDB.HR.EMPLOYEES;

CREATE OR REPLACE WAREHOUSE CONSUMER_WH 
WAREHOUSE_SIZE ='X-SMALL'
AUTO_SUSPEND =180
AUTO_RESUME =TRUE
INITIALLY_SUSPENDED=TRUE

SHOW TABLES

SELECT * FROM INBOUND_SHARE_HRMSDB.HR.DEPARTMENTS;

SHOW SHARES 

SELECT * FROM INBOUND_SHARE_HRMSDB.HR.EMPLOYEES;