SHOW SHARES

SHOW DATABASES

CREATE OR REPLACE DATABASE READER_SHARE_HRMS_HRDB FROM SHARE VMQFECX.MKB58028.SHARE_HRMS_HR;

SHOW TABLES 

SELECT * FROM READER_SHARE_HRMS_HRDB.HR.EMPLOYEES;


CREATE OR REPLACE WAREHOUSE READER_WH 
WAREHOUSE_SIZE ='X-SMALL'
AUTO_SUSPEND =180
AUTO_RESUME =TRUE
INITIALLY_SUSPENDED=TRUE


SELECT * FROM READER_SHARE_HRMS_HRDB.HR.EMPLOYEES;


CREATE OR REPLACE USER USER_DANIEL  PASSWORD ='abc123'; 


GRANT USAGE ON READER_WH TO ROLE PUBLIC;

GRANT IMPORTED PRIVILEGES ON DATABASE READER_SHARE_HRMS_HRDB TO ROLE PUBLIC

GRANT USAGE ON DATABASE READER_SHARE_HRMS_HRDB TO ROLE PUBLIC;