USE DATABASE HRMS;

USE SCHEMA HR;

CREATE OR REPLACE SECURE VIEW HRMS.HR.VIEW_EMPLOYEES_SECURE   
AS
SELECT 
        E.EMPLOYEE_ID,
        E.HIRE_DATE,
        E.JOB_ID,
        E.SALARY
FROM HRMS.HR.EMPLOYEES E;

SHOW VIEWS; 

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.VIEWS
WHERE TABLE_NAME LIKE 'VIEW_EMPLOYEES_SECURE%'

GRANT SELECT ON VIEW HRMS.HR.VIEW_EMPLOYEES_SECURE TO SHARE SHARE_HRMS_HR;

SHOW GRANTS TO SHARE SHARE_HRMS_HR; 


CREATE OR REPLACE VIEW HRMS.HR.VIEW_EMPLOYEES 
AS
SELECT 
        E.EMPLOYEE_ID,
        E.HIRE_DATE,
        E.JOB_ID,
        E.SALARY
FROM HRMS.HR.EMPLOYEES E;


GRANT SELECT ON VIEW HRMS.HR.VIEW_EMPLOYEES TO SHARE SHARE_HRMS_HR;

ALTER SHARE  SHARE_HRMS_HR SET SECURE_OBJECTS_ONLY = FALSE;

GRANT USAGE ON DATABASE HRMS TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA   HR   TO ROLE PUBLIC;
GRANT SELECT ON VIEW_EMPLOYEES_SECURE TO ROLE PUBLIC;
GRANT SELECT ON VIEW_EMPLOYEES TO ROLE PUBLIC;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PUBLIC;

USE ROLE PUBLIC

SHOW VIEWS LIKE '%EMP%'

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE SALESDB;

CREATE OR REPLACE SCHEMA SALES;


CREATE TABLE DAILY_SALES
(
EMPLOYEE_ID NUMBER,
SALES_AMT   NUMBER(15,2),
SALE_DATE   DATE
)


INSERT INTO DAILY_SALES VALUES (150, 125 ,CURRENT_DATE );
INSERT INTO DAILY_SALES VALUES (151, 365 , CURRENT_DATE);
INSERT INTO DAILY_SALES VALUES (152, 879 , CURRENT_DATE);
INSERT INTO DAILY_SALES VALUES (153,  777, CURRENT_DATE);

SELECT * FROM DAILY_SALES;

SELECT  
    E.EMPLOYEE_ID,
    E.HIRE_DATE,
    E.JOB_ID,
    E.SALARY,
    E.COMMISSION_PCT,
    S.SALES_AMT,
    S.SALE_DATE
FROM HRMS.HR.EMPLOYEES E, SALESDB.SALES.DAILY_SALES S
WHERE E.EMPLOYEE_ID = S.EMPLOYEE_ID

CREATE OR REPLACE SECURE VIEW HRMS.HR.SECURE_VIEW_EMPLOYEE_SALES
AS
SELECT  
    E.EMPLOYEE_ID,
    E.HIRE_DATE,
    E.JOB_ID,
    E.SALARY,
    E.COMMISSION_PCT,
    S.SALES_AMT,
    S.SALE_DATE
FROM 
      HRMS.HR.EMPLOYEES E, 
      SALESDB.SALES.DAILY_SALES S
WHERE E.EMPLOYEE_ID = S.EMPLOYEE_ID;


GRANT SELECT ON VIEW HRMS.HR.SECURE_VIEW_EMPLOYEE_SALES TO SHARE SHARE_HRMS_HR;

GRANT SELECT ON ALL TABLES IN DATABASE SALESDB        TO SHARE SHARE_HRMS_HR;
GRANT SELECT ON ALL TABLES IN SCHEMA   SALESDB.SALES  TO SHARE SHARE_HRMS_HR;

GRANT REFERENCE_USAGE ON DATABASE SALESDB TO SHARE SHARE_HRMS_HR;


GRANT SELECT ON VIEW HRMS.HR.SECURE_VIEW_EMPLOYEE_SALES TO SHARE SHARE_HRMS_HR;