USE DATABASE HRMS

USE SCHEMA HR

SHOW TABLES; 

CREATE OR REPLACE SHARE SHARE_HRMS_HR;  

SHOW SHARES

GRANT USAGE ON DATABASE HRMS               TO SHARE SHARE_HRMS_HR;
GRANT USAGE ON SCHEMA   HRMS.HR            TO SHARE SHARE_HRMS_HR;
GRANT SELECT ON TABLE   HRMS.HR.EMPLOYEES  TO SHARE SHARE_HRMS_HR;


SHOW GRANTS TO SHARE SHARE_HRMS_HR;  DROP ACCOUNT CONSUMER_ACCOUNT

GRANT INSERT ON TABLE   HRMS.HR.EMPLOYEES  TO SHARE SHARE_HRMS_HR;

USE ROLE ORGADMIN  UNDROP ACCOUNT CONSUMER_ACCOUNT

SHOW ACCOUNTS 

CREATE ACCOUNT CONSUMER_ACCOUNT
    ADMIN_NAME      = 'CONSUMER'
    ADMIN_PASSWORD  = 'Consumer@1234' 
    EMAIL           = 'learn2cloud@gmail.com'
    EDITION         =  STANDARD
 -- REGION          =  snowflake_region_id

 
USE ROLE ACCOUNTADMIN


ALTER SHARE SHARE_HRMS_HR ADD ACCOUNT =DIB21029


GRANT SELECT ON TABLE   HRMS.HR.DEPARTMENTS  TO SHARE SHARE_HRMS_HR;


GRANT SELECT ON ALL TABLES IN DATABASE HRMS     TO SHARE SHARE_HRMS_HR;
GRANT SELECT ON ALL TABLES IN SCHEMA   HRMS.HR  TO SHARE SHARE_HRMS_HR;


SHOW SHARES


CREATE TABLE HRMS.HR.TEST_TABLE_SHARE_VISIBLITY 
(
A       NUMBER
)


GRANT SELECT ON TABLE HRMS.HR.TEST_TABLE_SHARE_VISIBLITY TO SHARE SHARE_HRMS_HR;

SELECT * FROM HRMS.HR.EMPLOYEES;

UPDATE HRMS.HR.EMPLOYEES
SET SALARY =0
WHERE EMPLOYEE_ID =100;



--  READER ACCOUNT