USE DATABASE HRMS;


USE SCHEMA HR;


CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES
AS
SELECT * FROM HRMS.HR.EMPLOYEES ;


SELECT * FROM MVW_EMPLOYEES;

CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES
AS
SELECT 
    FIRST_NAME,
    LAST_NAME,
    FIRST_NAME||' '||LAST_NAME FULL_NAME,
    EMAIL,
    PHONE_NUMBER
FROM HRMS.HR.EMPLOYEES ;

SELECT * FROM MVW_EMPLOYEES;


CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES
AS
SELECT * FROM HRMS.HR.EMPLOYEES
WHERE DEPARTMENT_ID =100;


SELECT * FROM MVW_EMPLOYEES;


CREATE OR REPLACE SECURE MATERIALIZED VIEW SECURE_MVW_EMPLOYEES
AS
SELECT 
    FIRST_NAME,
    LAST_NAME,
    FIRST_NAME||' '||LAST_NAME FULL_NAME,
    EMAIL,
    PHONE_NUMBER
FROM HRMS.HR.EMPLOYEES ;

SELECT * FROM SECURE_MVW_EMPLOYEES;


SHOW MATERIALIZED VIEWS;

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE ='MATERIALIZED VIEW';

SELECT * FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME  IN ('MVW_EMPLOYEES','SECURE_MVW_EMPLOYEES');



--Limitations of Materialized views 


CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES
AS
SELECT 
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    E.EMAIL,
    E.PHONE_NUMBER,
    E.HIRE_DATE,
    E.JOB_ID,
    E.SALARY,
    E.COMMISSION_PCT,
    E.MANAGER_ID,
    D.DEPARTMENT_NAME
FROM HRMS.HR.EMPLOYEES E INNER JOIN HRMS.HR.DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID =100;





--DML Operation on Materialized view

UPDATE MVW_EMPLOYEES
SET SALARY =100000 ;

--DDL operations on Materialized view

TRUNCATE MATERIALIZED VIEW MVW_EMPLOYEES;


--Group By in Materialized view query.

CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_GROUP_BY_DEPARTMENT_ID
AS
SELECT 
    MAX(SALARY)         MAX_SALARY,
    MIN(SALARY)         MIN_SALARY,
    MAX(COMMISSION_PCT) MAX_COMMISSION ,
    MIN(COMMISSION_PCT) MIN_COMMISSION,
    DEPARTMENT_ID
FROM HRMS.HR.EMPLOYEES 
GROUP BY DEPARTMENT_ID;

SELECT * FROM MVW_EMPLOYEES_GROUP_BY_DEPARTMENT_ID;


CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_GROUP_BY_DEPARTMENT_ID
AS
SELECT 
    MAX(SALARY)         MAX_SALARY,
    MIN(SALARY)         MIN_SALARY,
    MAX(COMMISSION_PCT) MAX_COMMISSION ,
    MIN(COMMISSION_PCT) MIN_COMMISSION
--    DEPARTMENT_ID
FROM HRMS.HR.EMPLOYEES 
GROUP BY DEPARTMENT_ID;

CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_GROUP_BY_DEPARTMENT_ID
AS
SELECT 
    MAX(SALARY)         MAX_SALARY,
    MIN(SALARY)         MIN_SALARY,
    MAX(COMMISSION_PCT) MAX_COMMISSION ,
    MIN(COMMISSION_PCT) MIN_COMMISSION,
   DEPARTMENT_ID
FROM HRMS.HR.EMPLOYEES 
--HAVING MIN(SALARY) >100
GROUP BY DEPARTMENT_ID;

--Set Operators

CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_SET_OPERATOR
AS
SELECT * FROM EMPLOYEES
MINUS
SELECT * FROM EMPLOYEES;

CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_SET_OPERATOR
AS
SELECT * FROM EMPLOYEES
UNION ALL
SELECT * FROM EMPLOYEES;


--non-deterministic functions.

CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_CURRENT_TIMESTAMP
AS
SELECT 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID
--    ,CURRENT_TIMESTAMP AS TIME_NOW
FROM EMPLOYEES;


--Streams

CREATE OR REPLACE STREAM STREAM_MVW_EMPLOYEES ON MATERIALIZED VIEW MVW_EMPLOYEES;


--Cloning 

CREATE TABLE MVW_EMPLOYEES_CLONE CLONE MVW_EMPLOYEES;


--Data Refresh when base table is updated.


SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID=100;

SELECT * FROM MVW_EMPLOYEES
WHERE EMPLOYEE_ID=100;


UPDATE EMPLOYEES
SET COMMISSION_PCT =0.99
WHERE EMPLOYEE_ID=100;


SHOW MATERIALIZED VIEWS  LIKE 'MVW_EMPLOYEES';


--Clustering Materialized views.

CREATE OR REPLACE TABLE EMPLOYEES_DIM 
(
	EMPLOYEE_ID    NUMBER(6,0),
	FIRST_NAME     VARCHAR(20),
	LAST_NAME      VARCHAR(25),
	EMAIL          VARCHAR(25),
	PHONE_NUMBER   VARCHAR(20),
	HIRE_DATE      DATE,
	JOB_ID         VARCHAR(10),
	SALARY         NUMBER(8,2),
	COMMISSION_PCT NUMBER(2,2),
	MANAGER_ID     NUMBER(6,0),
	DEPARTMENT_ID NUMBER(4,0)
);

INSERT INTO EMPLOYEES_DIM SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES_DIM;

ALTER TABLE EMPLOYEES_DIM CLUSTER BY (DEPARTMENT_ID,JOB_ID);


SELECT 
        TABLE_CATALOG, 
        TABLE_SCHEMA, 
        TABLE_NAME, 
        CLUSTERING_KEY 
FROM INFORMATION_SCHEMA.TABLES WHERE CLUSTERING_KEY IS NOT NULL;


ALTER TABLE EMPLOYEES_DIM CLUSTER BY (MANAGER_ID,JOB_ID);


CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_DIM_CLUSTERED_BY_DEPARTMENT_ID 
CLUSTER BY(DEPARTMENT_ID,JOB_ID)
AS
SELECT * FROM EMPLOYEES_DIM;


CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE
CLUSTER BY(HIRE_DATE,JOB_ID)
AS
SELECT * FROM EMPLOYEES_DIM;


SHOW MATERIALIZED VIEWS  LIKE 'MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE';

--Suspending Materialized views.

SHOW MATERIALIZED VIEWS  LIKE 'MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE';

--SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME ='MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE';


SELECT * FROM MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE;


ALTER MATERIALIZED VIEW MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE SUSPEND ;


ALTER MATERIALIZED VIEW MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE RESUME ;


--Making changes to the underlying table structure

--Adding a new column.

ALTER TABLE EMPLOYEES_DIM ADD COLUMN DEPARTMENT_NAME VARCHAR(100);

UPDATE EMPLOYEES_DIM
SET DEPARTMENT_NAME ='Happy Department';

DESC TABLE EMPLOYEES_DIM;

SELECT * FROM MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE;


CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE
CLUSTER BY(HIRE_DATE,JOB_ID)
AS
SELECT * FROM EMPLOYEES_DIM;


--Dropping a column from the underlying table.

ALTER TABLE EMPLOYEES_DIM DROP COLUMN DEPARTMENT_NAME ;

SELECT * FROM MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE;

SHOW MATERIALIZED VIEWS  LIKE 'MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE';

ALTER MATERIALIZED VIEW MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE RESUME ;

CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE
CLUSTER BY(HIRE_DATE,JOB_ID)
AS
SELECT * FROM EMPLOYEES_DIM;


--Credit Consumption by Materialized view for a given Date range

SELECT * FROM TABLE(INFORMATION_SCHEMA.MATERIALIZED_VIEW_REFRESH_HISTORY(
    DATE_RANGE_START=>DATEADD(H, -48, CURRENT_TIMESTAMP)));


SELECT * FROM TABLE(INFORMATION_SCHEMA.MATERIALIZED_VIEW_REFRESH_HISTORY(
    DATE_RANGE_START=>'2024-04-01 00:00:00.000',
    DATE_RANGE_END=>'2024-05-30 20:00:00.000'));


SELECT SUM(CREDITS_USED) CREDITS_USED,MATERIALIZED_VIEW_NAME FROM TABLE(INFORMATION_SCHEMA.MATERIALIZED_VIEW_REFRESH_HISTORY(
    DATE_RANGE_START=>'2024-04-01 00:00:00.000',
    DATE_RANGE_END=>'2024-05-30 20:00:00.000'))
GROUP BY MATERIALIZED_VIEW_NAME;













--Cleanup

SHOW MATERIALIZED VIEWS;


DROP MATERIALIZED VIEW MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE;


--Modify DataType of Columns in the view

ALTER TABLE EMPLOYEES_DIM MODIFY COLUMN DEPARTMENT_NAME STRING;


SELECT * FROM MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE;

SHOW MATERIALIZED VIEWS  LIKE 'MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE';


CREATE OR REPLACE MATERIALIZED VIEW MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE
CLUSTER BY(HIRE_DATE,JOB_ID)
AS
SELECT * FROM EMPLOYEES_DIM;


SELECT * FROM MVW_EMPLOYEES_DIM_CLUSTERED_BY_HIRE_DATE;


SELECT COUNT(*) FROM MV_EMPLOYEE_EMAIL_PHONE
WHERE EMAIL LIKE '@GMAIL.COM' AND PHONE_NUMBER LIKE '847*'