USE DATABASE HRMS;


CREATE OR REPLACE SCHEMA ZEROCOPY;


CREATE TABLE ZEROCOPY.EMPLOYEES_SOURCE
AS
SELECT * FROM HRMS.HR.EMPLOYEES LIMIT 100;


SELECT  * FROM EMPLOYEES_SOURCE ;


GRANT SELECT,INSERT,UPDATE ON TABLE EMPLOYEES_SOURCE TO ROLE PUBLIC;


SHOW GRANTS ON TABLE EMPLOYEES_SOURCE;


CREATE OR REPLACE TABLE EMPLOYEES_REPLICA  CLONE EMPLOYEES_SOURCE;

SHOW TABLES;

SHOW GRANTS ON TABLE EMPLOYEES_REPLICA;

DROP TABLE EMPLOYEES_REPLICA;


CREATE TABLE EMPLOYEES_REPLICA  CLONE EMPLOYEES_SOURCE COPY GRANTS;


SHOW GRANTS ON TABLE EMPLOYEES_REPLICA;


SELECT COUNT(*) FROM EMPLOYEES_REPLICA;


SELECT COUNT(*) FROM EMPLOYEES_SOURCE;


SELECT * FROM EMPLOYEES_REPLICA
MINUS
SELECT * FROM EMPLOYEES_SOURCE;


SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME IN ('EMPLOYEES_SOURCE','EMPLOYEES_REPLICA') ;


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE TABLE_NAME IN ('EMPLOYEES_SOURCE','EMPLOYEES_REPLICA') 
AND DELETED='FALSE'



INSERT INTO EMPLOYEES_REPLICA 
SELECT E1.* FROM EMPLOYEES_SOURCE E1, EMPLOYEES_SOURCE E2 LIMIT 1000 ;


SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME IN ('EMPLOYEES_SOURCE','EMPLOYEES_REPLICA') ;


--CLONING TRANIENT & TEMPORARY TABLES

CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_EMPLOYEES_SOURCE 
AS
    SELECT * FROM HRMS.HR.EMPLOYEES LIMIT 100;


SELECT * FROM  TRANSIENT_EMPLOYEES_SOURCE 


CREATE OR REPLACE TABLE EMPLOYEES_REPLICA CLONE TRANSIENT_EMPLOYEES_SOURCE ;


CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_EMPLOYEES_REPLICA  CLONE TRANSIENT_EMPLOYEES_SOURCE ;


SHOW TABLES


CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_EMPLOYEES_SOURCE 
AS
    SELECT * FROM HRMS.HR.EMPLOYEES LIMIT 100;


SELECT * FROM  TEMPORARY_EMPLOYEES_SOURCE ;


CREATE OR REPLACE  TABLE EMPLOYEES_REPLICA  CLONE TEMPORARY_EMPLOYEES_SOURCE ;


CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_EMPLOYEES_REPLICA  CLONE TEMPORARY_EMPLOYEES_SOURCE ;


CREATE OR REPLACE  TEMPORARY TABLE TEMPORARY_EMPLOYEES_REPLICA  CLONE TEMPORARY_EMPLOYEES_SOURCE ;


CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_EMPLOYEES_REPLICA  CLONE EMPLOYEES_REPLICA;

CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_EMPLOYEES_REPLICA  CLONE EMPLOYEES_REPLICA;


CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_EMPLOYEES_REPLICA  CLONE TRANSIENT_EMPLOYEES_REPLICA ;--??


SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER LIMIT 10