USE DATABASE HRMS;

USE SCHEMA ZEROCOPY;

CREATE OR REPLACE TABLE EMPLOYEES_SNOWPIPE
(
    EMPLOYEE_ID         NUMBER ,
    FIRST_NAME          VARCHAR(20),
    LAST_NAME           VARCHAR(25),
    EMAIL               VARCHAR(25),
    PHONE_NUMBER        VARCHAR(20),
    HIRE_DATE           DATE,
    JOB_ID              VARCHAR(10),
    SALARY              NUMBER(8, 2),
    COMMISSION_PCT      NUMBER(2, 2),
    MANAGER_ID          NUMBER(6),
    DEPARTMENT_ID       NUMBER(4)
);

CREATE OR REPLACE FILE FORMAT HRMS.ZEROCOPY.CSV_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0;

CREATE OR REPLACE STAGE HRMS.ZEROCOPY.AWS_PIPE_CSV_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://learn2cloud-snowflake/snowpipe/csv/'
FILE_FORMAT = CSV_PIPE_FILEFORMAT;


CREATE OR REPLACE PIPE PIPE_EMPLOYEES
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE FROM @AWS_PIPE_CSV_STAGE;


CREATE OR REPLACE PIPE PIPE_EMPLOYEES_REPLICA CLONE PIPE_EMPLOYEES;


CREATE OR REPLACE SCHEMA ZEROCLONE ;


CREATE OR REPLACE TABLE EMPLOYEES_SNOWPIPE
(
    EMPLOYEE_ID         NUMBER ,
    FIRST_NAME          VARCHAR(20),
    LAST_NAME           VARCHAR(25),
    EMAIL               VARCHAR(25),
    PHONE_NUMBER        VARCHAR(20),
    HIRE_DATE           DATE,
    JOB_ID              VARCHAR(10),
    SALARY              NUMBER(8, 2),
    COMMISSION_PCT      NUMBER(2, 2),
    MANAGER_ID          NUMBER(6),
    DEPARTMENT_ID       NUMBER(4)
);


CREATE OR REPLACE FILE FORMAT CSV_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0 ;


CREATE OR REPLACE STAGE AWS_PIPE_CSV_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://learn2cloud-snowflake/snowpipe/csv/'
FILE_FORMAT = CSV_PIPE_FILEFORMAT;



CREATE OR REPLACE PIPE PIPE_EMPLOYEES
AUTO_INGEST=TRUE
AS
COPY INTO EMPLOYEES_SNOWPIPE FROM @AWS_PIPE_CSV_STAGE;


CREATE OR REPLACE VIEW VIEW_EMPLOYEES
AS
SELECT * FROM EMPLOYEES_SNOWPIPE;


CREATE OR REPLACE SCHEMA ZEROCLONE_REPLICA CLONE ZEROCLONE;


SHOW PIPES;

SHOW VIEWS;

SHOW STAGES;

SHOW FILE FORMATS;

--DATABASE CLONING

CREATE OR REPLACE DATABASE ZEROCOPYDB;


CREATE OR REPLACE SCHEMA ZEROCOPY1;


CREATE OR REPLACE SCHEMA ZEROCOPY2;

SHOW SCHEMAS;


CREATE OR REPLACE DATABASE ZEROCOPYDB_REPLICA CLONE ZEROCOPYDB ;

SHOW DATABASES LIKE 'ZEROCOPYDB%';


SHOW SCHEMAS;