USE DATABASE HRMS;

USE SCHEMA ZEROCOPY;

CREATE OR REPLACE SEQUENCE SEQ_EMPLOYEE_ID  START =1 


CREATE OR REPLACE TABLE EMPLOYEES_SEQ_SOURCE
(
    EMPLOYEE_ID         NUMBER DEFAULT SEQ_EMPLOYEE_ID.NEXTVAL,
    FIRST_NAME          VARCHAR(20),
    LAST_NAME           VARCHAR(25),
    EMAIL               VARCHAR(25),
    PHONE_NUMBER        VARCHAR(20),
    HIRE_DATE           DATE,
    JOB_ID              VARCHAR(10),
    SALARY              NUMBER(8, 2),
    COMMISSION_PCT      NUMBER(2, 2),
    MANAGER_ID          NUMBER(6),
    DEPARTMENT_ID       NUMBER(4)
);



CREATE OR REPLACE TABLE EMPLOYEES_SEQ_REPLICA  CLONE EMPLOYEES_SEQ_SOURCE ;


SELECT GET_DDL('TABLE','EMPLOYEES_SEQ_REPLICA')


CREATE OR REPLACE SEQUENCE SEQ_EMPLOYEE_ID_REPLICA  CLONE SEQ_EMPLOYEE_ID;


ALTER TABLE EMPLOYEES_SEQ_REPLICA MODIFY COLUMN EMPLOYEE_ID SET DEFAULT SEQ_EMPLOYEE_ID_REPLICA ;


SELECT GET_DDL('TABLE','EMPLOYEES_SEQ_REPLICA')


CREATE OR REPLACE FILE FORMAT HRMS.ZEROCOPY.CSV_ETL_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0;


CREATE OR REPLACE FILE FORMAT CSV_ETL_FILEFORMAT_REPLICA CLONE  CSV_ETL_FILEFORMAT;


SHOW FILE FORMATS



CREATE OR REPLACE STAGE HRMS.ZEROCOPY.AWS_ETL_CSV_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://learn2cloud-snowflake/loadingdata/csv/'
FILE_FORMAT = CSV_ETL_FILEFORMAT

 
CREATE OR REPLACE STAGE AWS_ETL_CSV_STAGE_REPLICA CLONE  AWS_ETL_CSV_STAGE;


DESCRIBE STAGE AWS_ETL_CSV_STAGE_REPLICA


ALTER STAGE AWS_ETL_CSV_STAGE_REPLICA SET FILE_FORMAT = CSV_ETL_FILEFORMAT_REPLICA;


-- STREAM CLONING
CREATE OR REPLACE TABLE EMPLOYEES_CDC
 (
    EMPLOYEE_ID         NUMBER ,
    FIRST_NAME          VARCHAR(20),
    LAST_NAME           VARCHAR(25),
    EMAIL               VARCHAR(25),
    PHONE_NUMBER        VARCHAR(20),
    HIRE_DATE           DATE,
    JOB_ID              VARCHAR(10),
    SALARY              NUMBER(8, 2),
    COMMISSION_PCT      NUMBER(2, 2),
    MANAGER_ID          NUMBER(6),
    DEPARTMENT_ID       NUMBER(4)
);
 
CREATE OR REPLACE STREAM STREAM_EMPLOYEES_CDC ON TABLE EMPLOYEES_CDC ;

INSERT INTO EMPLOYEES_CDC  SELECT * FROM HRMS.HR.EMPLOYEES LIMIT 100 ;

SELECT * FROM STREAM_EMPLOYEES_CDC ;

CREATE OR REPLACE STREAM STREAM_EMPLOYEES_CDC_REPLICA CLONE STREAM_EMPLOYEES_CDC;

SELECT * FROM STREAM_EMPLOYEES_CDC_REPLICA ;

SHOW STREAMS

SELECT * FROM STREAM_EMPLOYEES_CDC 
MINUS
SELECT * FROM STREAM_EMPLOYEES_CDC_REPLICA ;


--TASK CLONING

CREATE OR REPLACE TASK TASK_EMPLOYEES
WAREHOUSE =COMPUTE_WH
SCHEDULE ='60 MINUTES'
AS
SELECT CURRENT_USER ();


ALTER TASK TASK_EMPLOYEES RESUME;


CREATE TASK TASK_EMPLOYEES_REPLICA CLONE TASK_EMPLOYEES ;


SHOW TASKS