USE DATABASE HRMS;

USE SCHEMA ZEROCOPY;

CREATE OR REPLACE TABLE ZEROCOPY.EMPLOYEES_SOURCE
AS
SELECT * FROM HRMS.HR.EMPLOYEES LIMIT 100;

SET TS1 = CURRENT_TIMESTAMP;
SELECT $TS1


SELECT * FROM ZEROCOPY.EMPLOYEES_SOURCE;


UPDATE ZEROCOPY.EMPLOYEES_SOURCE SET SALARY =100000 ; --01b82077-0004-1cd7-0053-be070070bab2


SELECT * FROM ZEROCOPY.EMPLOYEES_SOURCE;


CREATE OR REPLACE TABLE EMPLOYEES_REPLICA_TIMETRAVEL_TS CLONE EMPLOYEES_SOURCE AT(TIMESTAMP => $TS1); 


SELECT * FROM EMPLOYEES_REPLICA_TIMETRAVEL_TS;

CREATE OR REPLACE TABLE EMPLOYEES_REPLICA_TIMETRAVEL_QUERY_ID CLONE EMPLOYEES_SOURCE BEFORE(STATEMENT => '01b82077-0004-1cd7-0053-be070070bab2');


SELECT * FROM EMPLOYEES_REPLICA_TIMETRAVEL_QUERY_ID;


--TIME TRAVEL SCHEMA 

CREATE OR REPLACE SCHEMA ZEROCOPY;

SHOW OBJECTS


CREATE TABLE ZEROCOPY.EMPLOYEES_SOURCE --TABLE 1
AS
SELECT * FROM HRMS.HR.EMPLOYEES LIMIT 100;

SHOW OBJECTS


CREATE OR REPLACE TABLE EMPLOYEES_REPLICA  CLONE EMPLOYEES_SOURCE ; --TABLE 2

CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_EMPLOYEES_SOURCE CLONE EMPLOYEES_SOURCE; --TABLE 3

SET TS2 = CURRENT_TIMESTAMP;

SHOW OBJECTS 

CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_EMPLOYEES_REPLICA  CLONE TRANSIENT_EMPLOYEES_SOURCE ; --TABLE 4

SHOW OBJECTS;


CREATE OR REPLACE SCHEMA ZEROCOPY_TIMETRAVEL_TS  CLONE ZEROCOPY AT(TIMESTAMP => $TS2); 

SHOW OBJECTS;



--TIME TRAVEL DATABASES

CREATE OR REPLACE DATABASE ZEROCOPYDB;

SHOW SCHEMAS

CREATE OR REPLACE SCHEMA ZEROCOPY1;

SHOW SCHEMAS

SET TS3 = CURRENT_TIMESTAMP;



CREATE OR REPLACE SCHEMA ZEROCOPY2; 


SHOW SCHEMAS;


CREATE OR REPLACE DATABASE ZEROCOPYDB_REPLICA_TIMETRAVEL_TS CLONE ZEROCOPYDB AT(TIMESTAMP => $TS3); 


SHOW SCHEMAS;


USE DATABASE ZEROCOPYDB;


SHOW SCHEMAS;