USE DATABASE HRMS;

USE SCHEMA ETL;

CREATE OR REPLACE FILE FORMAT HRMS.ETL.CSV_ETL_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0
NULL_IF = ('Null','NULL')
FIELD_OPTIONALLY_ENCLOSED_BY = '"'        
TRIM_SPACE=TRUE
COMPRESSION=AUTO;


CREATE OR REPLACE STAGE HRMS.ETL.AWS_ETL_CSV_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://learn2cloud-snowflake/loadingdata/csv/'
FILE_FORMAT = CSV_ETL_FILEFORMAT


CREATE OR REPLACE TABLE EMPLOYEES_COPY
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT DECIMAL(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);


LIST @AWS_ETL_CSV_STAGE;

COPY INTO HRMS.ETL.EMPLOYEES_COPY FROM @AWS_ETL_CSV_STAGE;


SELECT * FROM EMPLOYEES_COPY;


TRUNCATE TABLE EMPLOYEES_COPY;

COPY INTO EMPLOYEES_COPY FROM @AWS_ETL_CSV_STAGE
FORCE=TRUE;

SELECT COUNT(*) FROM EMPLOYEES_COPY;


--Load a subset of Columns.

CREATE OR REPLACE TABLE EMPLOYEES_SUBSET
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25),
  DEPARTMENT_ID  NUMBER(6)
);


COPY INTO EMPLOYEES_SUBSET FROM @AWS_ETL_CSV_STAGE;


COPY INTO EMPLOYEES_SUBSET FROM(SELECT T.$1,T.$2,T.$3,T.$11 FROM @AWS_ETL_CSV_STAGE T);

SELECT T.$1,T.$2,T.$3,T.$11 FROM @AWS_ETL_CSV_STAGE T;

SELECT $1, $2, $3,$11 FROM @AWS_ETL_CSV_STAGE T;

SELECT * FROM EMPLOYEES_SUBSET;


CREATE OR REPLACE TABLE EMPLOYEES_SUBSET
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25),
  DEPARTMENT_ID  NUMBER(6),
  FILE_NAME      VARCHAR(50)
);


COPY INTO EMPLOYEES_SUBSET FROM(SELECT T.$1,T.$2,T.$3,T.$11,METADATA$FILENAME FROM @AWS_ETL_CSV_STAGE T);

SELECT * FROM EMPLOYEES_SUBSET;


CREATE OR REPLACE TABLE EMPLOYEES_SUBSET_AUTO
(
  EMPLOYEE_ID    NUMBER(6)  AUTOINCREMENT START 1 INCREMENT 1,
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  DEPARTMENT_ID  NUMBER(6),
  FILE_NAME      VARCHAR(50)
);


COPY INTO EMPLOYEES_SUBSET_AUTO(FIRST_NAME,LAST_NAME,DEPARTMENT_ID,FILE_NAME) FROM 
                (SELECT T.$2,T.$3,t.$11,METADATA$FILENAME FROM @AWS_ETL_CSV_STAGE T);


SELECT * FROM EMPLOYEES_SUBSET_AUTO;


--COPY OPTION FILES

CREATE OR REPLACE TABLE EMPLOYEES_FILES
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT DECIMAL(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);

LIST @AWS_ETL_CSV_STAGE;


COPY INTO EMPLOYEES_FILES FROM @AWS_ETL_CSV_STAGE 
FILES=('employees_part_006.csv')


SELECT * FROM EMPLOYEES_FILES;


LIST @AWS_ETL_CSV_STAGE;


--COPY OPTION PATTERN

CREATE OR REPLACE TABLE EMPLOYEES_COPY_PATTERN
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);

LIST @AWS_ETL_CSV_STAGE;

COPY INTO EMPLOYEES_COPY_PATTERN FROM @AWS_ETL_CSV_STAGE
PATTERN='.*employees.*[.]csv'

SELECT * FROM EMPLOYEES_COPY_PATTERN;

--COPY OPTION PURGE=TRUE

CREATE OR REPLACE TABLE EMPLOYEES_COPY_PURGE
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);

LIST @AWS_ETL_CSV_STAGE;

COPY INTO EMPLOYEES_COPY_PURGE FROM @AWS_ETL_CSV_STAGE
PURGE=TRUE
PATTERN='.*employees.*[.]csv'

SELECT * FROM EMPLOYEES_COPY_PURGE;



--COPY OPTION TRUNCATECOLUMNS=TRUE

CREATE OR REPLACE TABLE EMPLOYEES_COPY_TRUNCATECOLUMNS
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);



COPY INTO EMPLOYEES_COPY_TRUNCATECOLUMNS FROM @AWS_ETL_CSV_STAGE
FILES=('employees_part_006_trun_cols.csv')
TRUNCATECOLUMNS=TRUE


SELECT * FROM EMPLOYEES_COPY_TRUNCATECOLUMNS

--COPY OPTION ON ERROR.

CREATE OR REPLACE TABLE EMPLOYEES_COPY_ON_ERROR
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);
SELECT * FROM EMPLOYEES_COPY_ON_ERROR;

COPY INTO EMPLOYEES_COPY_ON_ERROR FROM @AWS_ETL_CSV_STAGE
ON_ERROR=ABORT_STATEMENT

COPY INTO EMPLOYEES_COPY_ON_ERROR FROM @AWS_ETL_CSV_STAGE
ON_ERROR=SKIP_FILE

COPY INTO EMPLOYEES_COPY_ON_ERROR FROM @AWS_ETL_CSV_STAGE
ON_ERROR=SKIP_FILE_6

COPY INTO EMPLOYEES_COPY_ON_ERROR FROM @AWS_ETL_CSV_STAGE
ON_ERROR='SKIP_FILE_10%'

COPY INTO EMPLOYEES_COPY_ON_ERROR FROM @AWS_ETL_CSV_STAGE
ON_ERROR=CONTINUE


--RETURN_FAILED_ONLY TRUE

CREATE OR REPLACE TABLE EMPLOYEES_COPY_RETURN_FAILED_ONLY
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT DECIMAL(15,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);

LIST @AWS_ETL_CSV_STAGE

COPY INTO EMPLOYEES_COPY_RETURN_FAILED_ONLY FROM @AWS_ETL_CSV_STAGE
ON_ERROR=CONTINUE
RETURN_FAILED_ONLY=TRUE



--SIZE_LIMIT

CREATE OR REPLACE TABLE EMPLOYEES_SIZE_LIMIT
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);

LIST @AWS_ETL_CSV_STAGE


COPY INTO EMPLOYEES_SIZE_LIMIT FROM @AWS_ETL_CSV_STAGE
SIZE_LIMIT=10000000

SELECT * FROM EMPLOYEES_SIZE_LIMIT;

SHOW PARAMETERS LIKE '%STATEMENT_TIMEOUT_IN_SECONDS%' FOR WAREHOUSE COMPUTE_WH;



--VALIDATION_MODE

CREATE OR REPLACE TABLE EMPLOYEES_COPY_VALIDATION
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         VARCHAR(100),
  COMMISSION_PCT DECIMAL(15,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);

LIST @AWS_ETL_CSV_STAGE

COPY INTO EMPLOYEES_COPY_VALIDATION FROM @AWS_ETL_CSV_STAGE
VALIDATION_MODE=RETURN_ALL_ERRORS

COPY INTO EMPLOYEES_COPY_VALIDATION FROM @AWS_ETL_CSV_STAGE
VALIDATION_MODE=RETURN_ERRORS


COPY INTO EMPLOYEES_COPY_VALIDATION FROM @AWS_ETL_CSV_STAGE
VALIDATION_MODE=RETURN_5_ROWS



--LOADING DATA OVERRIDING THE FILE FORMAT

CREATE OR REPLACE TABLE EMPLOYEES_OVERRIDE
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT DECIMAL(15,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);


LIST @AWS_ETL_CSV_STAGE

COPY INTO EMPLOYEES_OVERRIDE FROM @AWS_ETL_CSV_STAGE

COPY INTO EMPLOYEES_OVERRIDE FROM @AWS_ETL_CSV_STAGE
FILE_FORMAT  = (TYPE=CSV FIELD_DELIMITER='|',SKIP_HEADER=1,NULL_IF = ('Null','NULL'))




TRUNCATE TABLE EMPLOYEES_OVERRIDE;


CREATE OR REPLACE FILE FORMAT HRMS.ETL.CSV_ETL_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = '|'
SKIP_HEADER = 1
NULL_IF = ('Null','NULL')
FIELD_OPTIONALLY_ENCLOSED_BY = '"'        
TRIM_SPACE=TRUE
COMPRESSION=AUTO;

TRUNCATE TABLE EMPLOYEES_OVERRIDE;

COPY INTO EMPLOYEES_OVERRIDE FROM @AWS_ETL_CSV_STAGE
FILE_FORMAT  = CSV_ETL_PIPE_FILEFORMAT




--LOADING DATA WITHOUT A STAGE

LIST @AWS_ETL_CSV_STAGE;

COPY INTO EMPLOYEES_COPY
  FROM 's3://learn2cloud-snowflake/loadingdata/csv/'
  CREDENTIALS=(AWS_KEY_ID='$AWS_ACCESS_KEY_ID' AWS_SECRET_KEY='$AWS_SECRET_ACCESS_KEY')
  FILE_FORMAT = (FORMAT_NAME = CSV_ETL_PIPE_FILEFORMAT)






--Transforming Data

CREATE OR REPLACE TABLE EMPLOYEES_CASE_TRANSFORM
(
  EMPLOYEE_ID    NUMBER(6)  ,
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25),
  FULL_NAME      VARCHAR(100), 
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  SALARY_BAND    VARCHAR(10),
  COMMISSION_PCT DECIMAL(2,2),
  COMMISSION_IND CHAR(1),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4),
  FILE_NAME      VARCHAR(50),
  INSERT_DATE    DATE         DEFAULT CURRENT_DATE,
  UPDATE_DATE    DATE         DEFAULT CURRENT_DATE
);

CREATE OR REPLACE SEQUENCE EMP_SEQ START WITH 1 ,INCREMENT BY 1 ORDER;

COPY INTO EMPLOYEES_CASE_TRANSFORM(
                                    EMPLOYEE_ID,FIRST_NAME,LAST_NAME,FULL_NAME,                                 
                                    EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,SALARY_BAND,COMMISSION_PCT,COMMISSION_IND,MANAGER_ID,DEPARTMENT_ID,FILE_NAME
                                  ) 
                            FROM 
                              (
                              SELECT 
                                    EMP_SEQ.NEXTVAL, 
                                    T.$2,
                                    T.$3, 
                                    TRIM(T.$2||' '||T.$3),
                                    T.$4,
                                    T.$5,
                                    T.$6,
                                    T.$7,
                               CAST(T.$8 AS DECIMAL(8,2)),
                               CASE 
                                    WHEN CAST($8 AS DECIMAL(8,2)) BETWEEN 0 AND 1000 THEN 'BAND 1'
                                    WHEN CAST($8 AS DECIMAL(8,2)) BETWEEN 1001 AND 2000 THEN 'BAND 2'
                                    WHEN CAST($8 AS DECIMAL(8,2)) BETWEEN 2001 AND 3000 THEN 'BAND 3'
                                    WHEN CAST($8 AS DECIMAL(8,2)) BETWEEN 3001 AND 4000 THEN 'BAND 4'
                                    WHEN CAST($8 AS DECIMAL(8,2)) BETWEEN 4001 AND 5000 THEN 'BAND 5'
                                    WHEN CAST($8 AS DECIMAL(8,2)) > 5000 THEN 'BAND 6' ELSE NULL
                              END, 
                              TRY_CAST(T.$9 AS DECIMAL(2,2)),
                             CASE  
                                 WHEN T.$9 IS NULL THEN 'N' ELSE 'Y' END,
                                 T.$10,
                                 T.$11,
                                 METADATA$FILENAME 
                        FROM @AWS_ETL_CSV_STAGE T
                        )
RETURN_FAILED_ONLY=TRUE
ON_ERROR=CONTINUE
SIZE_LIMIT=1000000                        
PATTERN='.*employees.*[.]csv'




SELECT TRY_CAST('20' AS DECIMAL(10,2)),TRY_CAST('TWENTY' AS DECIMAL(10,2))



SELECT CAST('TWENTY' AS DECIMAL(10,2))

                                        );

--RE-PROCESSING REJECTED ROWS

LIST @AWS_ETL_CSV_STAGE;

CREATE OR REPLACE TABLE EMPLOYEES_REPROCESS_REJECTS
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      VARCHAR(20) ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT DECIMAL(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
);


COPY INTO EMPLOYEES_REPROCESS_REJECTS FROM @AWS_ETL_CSV_STAGE
ON_ERROR=CONTINUE


SELECT * FROM EMPLOYEES_REPROCESS_RECORDS;


SELECT * FROM TABLE(VALIDATE(EMPLOYEES_REPROCESS_REJECTS,JOB_ID =>'01b632cd-0002-b662-0053-be0700519526'))

SELECT * FROM TABLE(VALIDATE(EMPLOYEES_REPROCESS_REJECTS,JOB_ID =>'_last'))


CREATE OR REPLACE TABLE DATAFIX_EMPLOYEES_REPROCESS_REJECTS
AS
SELECT REJECTED_RECORD FROM TABLE(VALIDATE(EMPLOYEES_REPROCESS_REJECTS,JOB_ID =>'01b632cd-0002-b662-0053-be0700519526'));



SELECT * FROM DATAFIX_EMPLOYEES_REPROCESS_REJECTS;

SELECT 
    
        SPLIT_PART(REJECTED_RECORD,',',1) AS EMPLOYEE_ID,   
        SPLIT_PART(REJECTED_RECORD,',',2) AS FIRST_NAME,
        SPLIT_PART(REJECTED_RECORD,',',3) AS LAST_NAME,        
        SPLIT_PART(REJECTED_RECORD,',',4) AS EMAIL,
        SPLIT_PART(REJECTED_RECORD,',',5) AS PHONE_NUMBER,
        SPLIT_PART(REJECTED_RECORD,',',6) AS HIRE_DATE,
        SPLIT_PART(REJECTED_RECORD,',',7) AS JOB_ID,
        SPLIT_PART(REJECTED_RECORD,',',8) AS SALARY,        
        SPLIT_PART(REJECTED_RECORD,',',9) AS COMMISSION_PCT,        
        SPLIT_PART(REJECTED_RECORD,',',10) AS MANAGER_ID,
        SPLIT_PART(REJECTED_RECORD,',',11) AS DEPARTMENT_ID
FROM DATAFIX_EMPLOYEES_REPROCESS_REJECTS;


SELECT 
    
        SPLIT_PART(REJECTED_RECORD,',',1) AS EMPLOYEE_ID,   
        SPLIT_PART(REJECTED_RECORD,',',2) AS FIRST_NAME,
        SPLIT_PART(REJECTED_RECORD,',',3) AS LAST_NAME,        
        SPLIT_PART(REJECTED_RECORD,',',4) AS EMAIL,
        SPLIT_PART(REJECTED_RECORD,',',5) AS PHONE_NUMBER,
        SPLIT_PART(REJECTED_RECORD,',',6) AS HIRE_DATE,
        SPLIT_PART(REJECTED_RECORD,',',7) AS JOB_ID,
        SPLIT_PART(REJECTED_RECORD,',',8) AS SALARY,
        REPLACE(SPLIT_PART(REJECTED_RECORD,',',8),'DOLLAR','') AS DATAFIXED_SALARY,        
        SPLIT_PART(REJECTED_RECORD,',',9) AS COMMISSION_PCT,       
        REPLACE (SPLIT_PART(REJECTED_RECORD,',',9),'NULL',NULL) AS DATAFIXED_COMMISSION_PCT,           
        SPLIT_PART(REJECTED_RECORD,',',10) AS MANAGER_ID,
        SPLIT_PART(REJECTED_RECORD,',',11) AS DEPARTMENT_ID        
FROM DATAFIX_EMPLOYEES_REPROCESS_REJECTS;



INSERT INTO EMPLOYEES_REPROCESS_REJECTS
SELECT 
    
        SPLIT_PART(REJECTED_RECORD,',',1) AS EMPLOYEE_ID,   
        SPLIT_PART(REJECTED_RECORD,',',2) AS FIRST_NAME,
        SPLIT_PART(REJECTED_RECORD,',',3) AS LAST_NAME,        
        SPLIT_PART(REJECTED_RECORD,',',4) AS EMAIL,
        SPLIT_PART(REJECTED_RECORD,',',5) AS PHONE_NUMBER,
        SPLIT_PART(REJECTED_RECORD,',',6) AS HIRE_DATE,
        SPLIT_PART(REJECTED_RECORD,',',7) AS JOB_ID,
        REPLACE(SPLIT_PART(REJECTED_RECORD,',',8),'DOLLAR','') AS DATAFIXED_SALARY,        
          REPLACE (SPLIT_PART(REJECTED_RECORD,',',9),'NULL',NULL) AS DATAFIXED_COMMISSION_PCT,            
        SPLIT_PART(REJECTED_RECORD,',',10) AS MANAGER_ID,
        SPLIT_PART(REJECTED_RECORD,',',11) AS DEPARTMENT_ID        
FROM DATAFIX_EMPLOYEES_REPROCESS_REJECTS;

SELECT * FROM EMPLOYEES_REPROCESS_REJECTS;



SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(TABLE_NAME=>'EMPLOYEES_REPROCESS_REJECTS', START_TIME=> DATEADD(HOURS, -1, CURRENT_TIMESTAMP())));