USE DATABASE HRMS;

USE SCHEMA ETL;


SELECT * FROM HRMS.HR.EMPLOYEES;


CREATE OR REPLACE FILE FORMAT HRMS.ETL.JSON_ETL_FILEFORMAT
TYPE = JSON;


CREATE OR REPLACE STAGE HRMS.ETL.AWS_ETL_JSON_STAGE_UNLOAD
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://learn2cloud-snowflake/unloadingdata/JSON/'
FILE_FORMAT = JSON_ETL_FILEFORMAT



COPY INTO @AWS_ETL_JSON_STAGE_UNLOAD/emp_json FROM (SELECT OBJECT_CONSTRUCT(*) FROM HRMS.HR.EMPLOYEES) 







