USE DATABASE HRMS;

USE SCHEMA ETL;

SELECT * FROM HRMS.HR.EMPLOYEES;

CREATE OR REPLACE FILE FORMAT HRMS.ETL.CSV_ETL_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0
NULL_IF = ('Null','NULL')
FIELD_OPTIONALLY_ENCLOSED_BY = '"'        
TRIM_SPACE=TRUE
COMPRESSION=NONE;

CREATE OR REPLACE STAGE HRMS.ETL.AWS_ETL_CSV_STAGE_UNLOAD
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://learn2cloud-snowflake/unloadingdata/csv/'
FILE_FORMAT = CSV_ETL_FILEFORMAT

COPY INTO @AWS_ETL_CSV_STAGE_UNLOAD FROM HRMS.HR.EMPLOYEES
OVERWRITE =TRUE

COPY INTO @AWS_ETL_CSV_STAGE_UNLOAD FROM HRMS.HR.EMPLOYEES
FILE_FORMAT = (TYPE = CSV COMPRESSION = NONE);

LIST @AWS_ETL_CSV_STAGE_UNLOAD

COPY INTO @AWS_ETL_CSV_STAGE_UNLOAD/emp  FROM HRMS.HR.EMPLOYEES



