USE DATABASE HRMS;

USE SCHEMA ETL;

SELECT * FROM HRMS.HR.EMPLOYEES;

CREATE OR REPLACE TABLE HRMS.ETL.EMPLOYEES_UNLOAD LIKE HRMS.HR.EMPLOYEES;

INSERT OVERWRITE INTO HRMS.ETL.EMPLOYEES_UNLOAD
SELECT E1.* FROM HRMS.HR.EMPLOYEES E1, HRMS.HR.EMPLOYEES E2 ,HRMS.HR.EMPLOYEES E3

COPY INTO @AWS_ETL_CSV_STAGE_UNLOAD/emp FROM HRMS.ETL.EMPLOYEES_UNLOAD

COPY INTO @AWS_ETL_CSV_STAGE_UNLOAD/emp_single FROM HRMS.ETL.EMPLOYEES_UNLOAD
SINGLE =TRUE
MAX_FILE_SIZE =250000000 
HEADER = TRUE
OVERWRITE =TRUE

