USE DATABASE HRMS;

USE SCHEMA HR;

--SAMPLE | TABLESAMPLE
--BERNOULLI | ROW
--SYSTEM | BLOCK
--REPEATABLE | SEED


--Fixed-size Row Sampling


SELECT * FROM HR.EMPLOYEES SAMPLE (10 ROWS);


SELECT * FROM HR.EMPLOYEES LIMIT 10;


--ROW|BERNOULLI  

SELECT * FROM HR.EMPLOYEES SAMPLE ROW (20);


SELECT * FROM HR.EMPLOYEES SAMPLE ROW (20) SEED(77);


SELECT * FROM HR.EMPLOYEES SAMPLE  (20) SEED(77);

SELECT * FROM HR.EMPLOYEES SAMPLE ROW (20) SEED(77)
MINUS
SELECT * FROM HR.EMPLOYEES SAMPLE ROW (20) SEED(77)



SELECT * FROM HR.EMPLOYEES SAMPLE BERNOULLI (20) SEED(77);


--SYSTEM | BLOCK


SELECT * FROM HR.EMPLOYEES SAMPLE SYSTEM (20);


SELECT * FROM HR.EMPLOYEES SAMPLE SYSTEM (20) SEED(99);


SELECT * FROM HR.EMPLOYEES SAMPLE SYSTEM (20) SEED(99);


SELECT * FROM HR.EMPLOYEES SAMPLE SYSTEM (20) SEED(99)
MINUS
SELECT * FROM HR.EMPLOYEES SAMPLE SYSTEM (20) SEED(99);


SELECT * FROM HR.EMPLOYEES SAMPLE BLOCK (20) SEED(99);


--Using 100% rows

SELECT * FROM HR.EMPLOYEES SAMPLE SYSTEM (100);


-- Using TABLESAMPLE instead of SAMPLE.

SELECT * FROM HR.EMPLOYEES TABLESAMPLE SYSTEM (100);


SELECT * FROM HR.EMPLOYEES SAMPLE SYSTEM (100)
MINUS
SELECT * FROM HR.EMPLOYEES TABLESAMPLE SYSTEM (100);


-- Using REPEATABLE instead of SEED.

SELECT * FROM HR.EMPLOYEES SAMPLE BLOCK (20) REPEATABLE(99);


SELECT * FROM HR.EMPLOYEES SAMPLE BLOCK (20) REPEATABLE(99)
MINUS
SELECT * FROM HR.EMPLOYEES SAMPLE BLOCK (20) SEED(99);

--Join between 2 tables that are sampled.

SELECT * FROM HR.EMPLOYEES E SAMPLE ROW (10)
                        JOIN  HR.DEPARTMENTS D 
ON E.DEPARTMENT_ID =D.DEPARTMENT_ID;


SELECT * FROM HR.EMPLOYEES E SAMPLE ROW (10)
                        JOIN  HR.DEPARTMENTS D 
ON E.DEPARTMENT_ID =D.DEPARTMENT_ID
WHERE JOB_ID ='SH_CLERK';


SELECT * FROM HR.EMPLOYEES E SAMPLE ROW (10) 
                        JOIN  HR.DEPARTMENTS D SAMPLE SYSTEM(50) 
ON E.DEPARTMENT_ID =D.DEPARTMENT_ID


SELECT * FROM HR.EMPLOYEES E SAMPLE ROW (10) SEED(51)
                        JOIN  HR.DEPARTMENTS D SAMPLE SYSTEM(50) SEED(74)
ON E.DEPARTMENT_ID =D.DEPARTMENT_ID




--Use Case Analytics on data using data sampling.


SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER TABLESAMPLE (10 ROWS);


SELECT APPROX_COUNT_DISTINCT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER; --147,446,833

SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER; --150,000,000


SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER TABLESAMPLE (10 ROWS);


SELECT  COUNT(*),
        C_MKTSEGMENT,
        COUNT(*)/(SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER) * 100 PCT_PER_SEGMENT  
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER 
GROUP BY C_MKTSEGMENT;




CREATE OR REPLACE TABLE CUSTOMER_MARKET_SEGMENT_ALL_ROWS
AS
SELECT  COUNT(*) ROW_COUNT,
        C_MKTSEGMENT,
         COUNT(*)/(SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER) * 100 PCT_PER_SEGMENT,  
        'ALL_ROWS' SAMPLING_TYPE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER 
GROUP BY C_MKTSEGMENT;



SELECT  COUNT(*) ,
        C_MKTSEGMENT,
        COUNT(*)/(SELECT APPROX_COUNT_DISTINCT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER 
                                     SAMPLE SYSTEM(10) SEED(65)) * 100 PCT_PER_SEGMENT      
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER SAMPLE SYSTEM (10) SEED(65) 
GROUP BY C_MKTSEGMENT;



CREATE OR REPLACE TABLE CUSTOMER_MARKET_SEGMENT_SYSTEM
AS
SELECT  COUNT(*) ROW_COUNT,
        C_MKTSEGMENT,
        COUNT(*)/(SELECT APPROX_COUNT_DISTINCT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER 
                                    SAMPLE SYSTEM(10) SEED(65)) * 100 PCT_PER_SEGMENT,
         'SYSTEM SAMPLING' SAMPLING_TYPE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER SAMPLE SYSTEM (10) SEED(65) 
GROUP BY C_MKTSEGMENT


SELECT * FROM CUSTOMER_MARKET_SEGMENT_ALL_ROWS
UNION ALL
SELECT * FROM CUSTOMER_MARKET_SEGMENT_SYSTEM
ORDER BY C_MKTSEGMENT,SAMPLING_TYPE