SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS ORDER BY FAILSAFE_BYTES DESC;


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS 
WHERE TABLE_NAME LIKE 'EMPLOYEES%' AND TABLE_SCHEMA ='RETENTION'


SELECT 	ID, 
		TABLE_NAME, 
		TABLE_SCHEMA,
        TABLE_CATALOG,
        FAILSAFE_BYTES/(1024*1024*1024) AS FAILSAFE_USED_GB,
		ACTIVE_BYTES / (1024*1024*1024) AS ACTIVE_USED_GB,
		TIME_TRAVEL_BYTES / (1024*1024*1024) AS TIME_TRAVEL_STORAGE_USED_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
ORDER BY ACTIVE_USED_GB DESC,TIME_TRAVEL_STORAGE_USED_GB DESC;