USE DATABASE TIMETRAVELER ;

USE  SCHEMA RETENTION;

CREATE OR REPLACE TABLE EMPLOYEES_UNDROP (
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20),
  LAST_NAME      VARCHAR(25) ,
  EMAIL          VARCHAR(25),
  PHONE_NUMBER   VARCHAR(20),
  HIRE_DATE      DATE ,
  JOB_ID         VARCHAR(10) ,
  SALARY         NUMBER(8,2),
  COMMISSION_PCT NUMBER(2,2),
  MANAGER_ID     NUMBER(6),
  DEPARTMENT_ID  NUMBER(4)
) DATA_RETENTION_TIME_IN_DAYS = 7;



INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 100, 'STEVEN', 'KING', 'SKING', '515.123.4567', TO_DATE('17-06-2003', 'DD-MM-YYYY'), 'AD_PRES', 24000, NULL, NULL, 90);

INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 101, 'NEENA', 'KOCHHAR', 'NKOCHHAR', '515.123.4568', TO_DATE('21-09-2005', 'DD-MM-YYYY'), 'AD_VP', 17000, NULL, 100, 90);

INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 102, 'LEX', 'DE HAAN', 'LDEHAAN', '515.123.4569', TO_DATE('13-01-2001', 'DD-MM-YYYY'), 'AD_VP', 17000, NULL, 100, 90);

INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 103, 'ALEXANDER', 'HUNOLD', 'AHUNOLD', '590.423.4567', TO_DATE('03-01-2006', 'DD-MM-YYYY'), 'IT_PROG', 9000, NULL, 102, 60);

INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 104, 'BRUCE', 'ERNST', 'BERNST', '590.423.4568', TO_DATE('21-05-2007', 'DD-MM-YYYY'), 'IT_PROG', 6000, NULL, 103, 60);

INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 105, 'DAVID', 'AUSTIN', 'DAUSTIN', '590.423.4569', TO_DATE('25-06-2005', 'DD-MM-YYYY'), 'IT_PROG', 4800, NULL, 103, 60);

INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 107, 'DIANA', 'LORENTZ', 'DLORENTZ', '590.423.5567', TO_DATE('07-02-2007', 'DD-MM-YYYY'), 'IT_PROG', 4200, NULL, 103, 60);

INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 108, 'NANCY', 'GREENBERG', 'NGREENBE', '515.124.4569', TO_DATE('17-08-2002', 'DD-MM-YYYY'), 'FI_MGR', 12008, NULL, 101, 100);

INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 109, 'DANIEL', 'FAVIET', 'DFAVIET', '515.124.4169', TO_DATE('16-08-2002', 'DD-MM-YYYY'), 'FI_ACCOUNT', 9000, NULL, 108, 100);

INSERT INTO EMPLOYEES_UNDROP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 110, 'JOHN', 'CHEN', 'JCHEN', '515.124.4269', TO_DATE('28-09-2005', 'DD-MM-YYYY'), 'FI_ACCOUNT', 8200, NULL, 108, 100);


SELECT * FROM EMPLOYEES_UNDROP;

DROP TABLE EMPLOYEES_UNDROP;

UNDROP TABLE EMPLOYEES_UNDROP;

SELECT * FROM EMPLOYEES_UNDROP;

DROP SCHEMA RETENTION ;

UNDROP SCHEMA RETENTION;

USE SCHEMA RETENTION;

SELECT * FROM EMPLOYEES_UNDROP;

DROP DATABASE TIMETRAVELER;

UNDROP DATABASE TIMETRAVELER;

USE DATABASE TIMETRAVELER ;

USE  SCHEMA RETENTION;

DROP TABLE EMPLOYEES_UNDROP;

CREATE OR REPLACE TABLE EMPLOYEES_UNDROP 
(
  EMPLOYEE_ID    NUMBER(6),
  FIRST_NAME     VARCHAR(20)
) DATA_RETENTION_TIME_IN_DAYS = 21;


UNDROP TABLE EMPLOYEES_UNDROP;

SELECT * FROM EMPLOYEES_UNDROP;


ALTER TABLE EMPLOYEES_UNDROP RENAME TO EMPLOYEES_UNDROP_2_COLS
