CREATE OR REPLACE DATABASE LOGGING; 

CREATE SCHEMA EVENT_LOGGING;


CREATE OR REPLACE EVENT TABLE LOGGING.EVENT_LOGGING.EVENTS;

CREATE OR REPLACE EVENT TABLE LOGGING.EVENT_LOGGING.TBL_EVENT_LOG;


SHOW EVENT TABLES ;


ALTER ACCOUNT SET EVENT_TABLE = LOGGING.EVENT_LOGGING.EVENTS;



CREATE OR REPLACE PROCEDURE LOGGING.EVENT_LOGGING.SP_DQ_EMPLOYEES(message string)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE 

V_DEPT_ID_NULL_COUNT    INTEGER;
V_EMP_ID_NULL_COUNT     INTEGER;
V_EMP_TOTAL_COUNT       INTEGER;

BEGIN

SYSTEM$LOG('TRACE','Program has begun '||:message );


SELECT COUNT(*) INTO :V_DEPT_ID_NULL_COUNT FROM HRMS.HR.EMPLOYEES WHERE DEPARTMENT_ID IS NULL;

SELECT COUNT(*) INTO :V_EMP_ID_NULL_COUNT FROM HRMS.HR.EMPLOYEES WHERE EMPLOYEE_ID IS NULL;

SELECT COUNT(*) INTO :V_EMP_TOTAL_COUNT FROM HRMS.HR.EMPLOYEES ;

IF (:V_DEPT_ID_NULL_COUNT>0) THEN 
    SYSTEM$LOG('DEBUG','In the IF Block-1.');

    SYSTEM$LOG('WARN','Department_ID is null');
    
END IF;

IF (:V_EMP_ID_NULL_COUNT>0) THEN 
    SYSTEM$LOG('DEBUG','In the IF Block-2.');

    SYSTEM$LOG('ERROR','Employee PK is null');

END IF;

IF (:V_EMP_TOTAL_COUNT=0) THEN 
    SYSTEM$LOG('DEBUG','In the IF Block-3.');

    SYSTEM$LOG('FATAL','Employee Table is empty');

END IF;

SYSTEM$LOG('INFO','Stored Proc name is SP_DQ_EMPLOYEES' );

SYSTEM$LOG('TRACE','Program ended.'||:message );
END;
$$



ALTER PROCEDURE LOGGING.EVENT_LOGGING.SP_DQ_EMPLOYEES(string) SET LOG_LEVEL=TRACE;

ALTER PROCEDURE LOGGING.EVENT_LOGGING.SP_DQ_EMPLOYEES(string) SET TRACE_LEVEL=ALWAYS;


CALL LOGGING.EVENT_LOGGING.SP_DQ_EMPLOYEES('Data Quality');



SELECT * FROM LOGGING.EVENT_LOGGING.EVENTS;

DESCRIBE EVENT TABLE EVENT_LOGGING.EVENTS;


DELETE TABLE EVENT_LOGGING.EVENTS; 

TRUNCATE TABLE EVENT_LOGGING.EVENTS;

SHOW EVENT TABLES;

ALTER ACCOUNT SET EVENT_TABLE = LOGGING.EVENT_LOGGING.TBL_EVENT_LOG;

SHOW PARAMETERS LIKE 'event_table' IN ACCOUNT;


ALTER ACCOUNT SET EVENT_TABLE = LOGGING.EVENT_LOGGING.EVENT;


DROP TABLE LOGGING.EVENT_LOGGING.EVENTS;

UNDROP TABLE LOGGING.EVENT_LOGGING.EVENTS;

SELECT * FROM LOGGING.EVENT_LOGGING.EVENTS;

ALTER TABLE EVENTS  CLUSTER BY (RECORD_TYPE);

ALTER TABLE EVENTS ADD SEARCH OPTIMIZATION ON EQUALITY(TIMESTAMP);

ALTER TABLE NEW_EVENTS RENAME TO EVENTS;


ALTER PROCEDURE LOGGING.EVENT_LOGGING.SP_DQ_EMPLOYEES(string) SET LOG_LEVEL=OFF;

ALTER PROCEDURE LOGGING.EVENT_LOGGING.SP_DQ_EMPLOYEES(string) SET TRACE_LEVEL=OFF;


SELECT *  FROM  INFORMATION_SCHEMA.EVENT_TABLES;


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.EVENT_USAGE_HISTORY;




ALTER DATABASE LOGGING SET LOG_LEVEL= TRACE;
ALTER DATABASE LOGGING SET TRACE_LEVEL= ALWAYS;

ALTER SCHEMA LOGGING.EVENT_LOGGING SET LOG_LEVEL=TRACE;
ALTER SCHEMA LOGGING.EVENT_LOGGING SET TRACE_LEVEL=ALWAYS;


ALTER ACCOUNT SET LOG_LEVEL =TRACE;
ALTER ACCOUNT SET TRACE_LEVEL =ALWAYS;


ALTER USER SET LOG_LEVEL =TRACE;
ALTER USER SET TRACE_LEVEL =ALWAYS;


ALTER SESSION SET LOG_LEVEL =TRACE;
ALTER SESSION SET TRACE_LEVEL =ALWAYS;


------------

CLEAN-UP SCRIPT

ALTER DATABASE LOGGING SET LOG_LEVEL= OFF;
ALTER DATABASE LOGGING SET TRACE_LEVEL= OFF;

ALTER SCHEMA LOGGING.EVENT_LOGGING SET LOG_LEVEL=OFF;
ALTER SCHEMA LOGGING.EVENT_LOGGING SET TRACE_LEVEL=OFF;


ALTER ACCOUNT SET LOG_LEVEL =OFF;
ALTER ACCOUNT SET TRACE_LEVEL =OFF;


ALTER USER SET LOG_LEVEL =OFF;
ALTER USER SET TRACE_LEVEL =OFF;


ALTER SESSION SET LOG_LEVEL =OFF;
ALTER SESSION SET TRACE_LEVEL =OFF;

ALTER PROCEDURE LOGGING.EVENT_LOGGING.SP_DQ_EMPLOYEES(string) SET LOG_LEVEL=OFF;
ALTER PROCEDURE LOGGING.EVENT_LOGGING.SP_DQ_EMPLOYEES(string) SET TRACE_LEVEL=OFF;



------

CREATE OR REPLACE PROCEDURE LOGGING.EVENT_LOGGING.SP_DQ_EMPLOYEES(message string)
RETURNS VARCHAR
LANGUAGE SQL
AS
DECLARE 

V_DEPT_ID_NULL_COUNT    INTEGER;
V_EMP_ID_NULL_COUNT     INTEGER;
V_EMP_TOTAL_COUNT       INTEGER;

BEGIN

SYSTEM$LOG('TRACE','Program has begun '||:message );


SELECT COUNT(*) INTO :V_DEPT_ID_NULL_COUNT FROM HRMS.HR.EMPLOYEES WHERE DEPARTMENT_ID IS NULL;

SELECT COUNT(*) INTO :V_EMP_ID_NULL_COUNT FROM HRMS.HR.EMPLOYEES WHERE EMPLOYEE_ID IS NULL;

SELECT COUNT(*) INTO :V_EMP_TOTAL_COUNT FROM HRMS.HR.EMPLOYEES ;

IF (:V_DEPT_ID_NULL_COUNT>0) THEN 
    SYSTEM$LOG('DEBUG','In the IF Block-1.');

    SYSTEM$LOG('WARN','Department_ID is null');
    
END IF;

IF (:V_EMP_ID_NULL_COUNT>0) THEN 
    SYSTEM$LOG('DEBUG','In the IF Block-2.');

    SYSTEM$LOG('ERROR','Employee PK is null');

END IF;

IF (:V_EMP_TOTAL_COUNT=0) THEN 
    SYSTEM$LOG('DEBUG','In the IF Block-3.');

    SYSTEM$LOG('FATAL','Employee Table is empty');

END IF;

SYSTEM$LOG('INFO','Stored Proc name is SP_DQ_EMPLOYEES' );

SYSTEM$LOG('TRACE','Program ended.'||:message );
END;

