USE DATABASE HRMS;

CREATE OR REPLACE SCHEMA SCHEDULE;

--Creating Tasks

CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE =COMPUTE_WH
SCHEDULE ='10 MINUTE'   --1 MINUTE(S)|37 MINUTE(S)|60 MINUTES|120 MINUTES|HOURS NOT ALLOWED
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES 
AS 
SELECT * FROM HR.EMPLOYEES;

SHOW TASKS;

SHOW TASKS  LIKE 'TASK_CREATE_TABLE'

DESCRIBE TASK TASK_CREATE_TABLE

ALTER TASK TASK_CREATE_TABLE  RESUME;

ALTER TASK TASK_CREATE_TABLE  SUSPEND;

SHOW TABLES;

EXECUTE TASK TASK_CREATE_TABLE;  


CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE =COMPUTE_WH
SCHEDULE ='USING CRON 0 7 * * 1-5 America/Chicago'   --Monday to Friday at 7:00 am Chicago Time.
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES 
AS 
SELECT * FROM HR.EMPLOYEES;



# __________ minute (0-59)
# | ________ hour (0-23)
# | | ______ day of month (1-31, or L)
# | | | ____ month (1-12, JAN-DEC)
# | | | | _ day of week (0-6, SUN-SAT, or L)
# | | | | |
# | | | | |
  * * * * *


DROP TASK TASK_CREATE_TABLE;



--Creating a Task without a schedule.


CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE =COMPUTE_WH
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_NOSCHEDULE 
AS 
SELECT * FROM HR.EMPLOYEES;


ALTER TASK TASK_CREATE_TABLE  RESUME;


EXECUTE TASK TASK_CREATE_TABLE;


SHOW TABLES ;


SHOW TASKS;

--Creating a Task without a Warehouse.

CREATE OR REPLACE TASK TASK_CREATE_TABLE  
SCHEDULE ='10 MINUTES'   --1 MINUTE|60 MINUTES|120 MINUTES
WAREHOUSE =COMPUTE_WH
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_NOWAREHOUSE 
AS 
SELECT * FROM HR.EMPLOYEES;

SHOW TABLES ;

SHOW TASKS;

ALTER TASK TASK_CREATE_TABLE  RESUME;

EXECUTE TASK TASK_CREATE_TABLE;


CREATE OR REPLACE TASK TASK_CREATE_TABLE  
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE ='XLARGE' --DEFAULT MEDIUM.
SCHEDULE ='10 MINUTES'   --1 MINUTE|60 MINUTES|120 MINUTES
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_NOWAREHOUSE_INITIAL_WAREHOUSE_SIZE 
AS
SELECT * FROM HR.EMPLOYEES;


ALTER TASK TASK_CREATE_TABLE  RESUME;

EXECUTE TASK TASK_CREATE_TABLE;

SHOW TABLES ;

SHOW TASKS;


--Using more than 1 SQL statement with a TASK

CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE =COMPUTE_WH
SCHEDULE ='1 MINUTE'
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_MULTISQL 
AS 
SELECT * FROM HR.EMPLOYEES
INSERT INTO SCHEDULE.EMPLOYEES_MULTISQL (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 209, 'JACK', 'ADAMS', 'JADAMS', '011.44.1644.429264', TO_DATE('23-04-2006', 'DD-MM-YYYY'), 'SA_REP', 8400, .20, 149, 80);



CREATE OR REPLACE TASK TASK_CREATE_TABLE
WAREHOUSE =COMPUTE_WH
SCHEDULE ='1 MINUTE'
AS
BEGIN

CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_MULTISQL_BLOCK 
AS 
SELECT * FROM HR.EMPLOYEES
WHERE 1=2;


INSERT INTO SCHEDULE.EMPLOYEES_MULTISQL_BLOCK (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
( 209, 'JACK', 'ADAMS', 'JADAMS', '011.44.1644.429264', TO_DATE('23-04-2006', 'DD-MM-YYYY'), 'SA_REP', 8400, .20, 149, 80);

END;


ALTER TASK TASK_CREATE_TABLE  RESUME;


EXECUTE TASK TASK_CREATE_TABLE;



SHOW TABLES LIKE 'EMPLOYEES_MULTISQL_BLOCK';


SELECT * FROM SCHEDULE.EMPLOYEES_MULTISQL_BLOCK;


CREATE OR REPLACE PROCEDURE SCHEDULE.SP_TASK_CREATE_TABLE()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
        CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_MULTISQL_SP 
        AS 
        SELECT * FROM HR.EMPLOYEES
        WHERE 1=2;

        
        INSERT INTO SCHEDULE.EMPLOYEES_MULTISQL_SP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES
        ( 209, 'JACK', 'SMITH', 'JSMITH', '011.44.1644.429264', TO_DATE('23-04-2006', 'DD-MM-YYYY'), 'SA_REP', 8400, .20, 149, 80);
END; 


CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE =COMPUTE_WH
SCHEDULE ='10 MINUTE'
AS
CALL SCHEDULE.SP_TASK_CREATE_TABLE();


ALTER TASK TASK_CREATE_TABLE  RESUME;

SHOW TABLES 


EXECUTE TASK TASK_CREATE_TABLE;

SHOW TABLES LIKE 'EMPLOYEES_MULTISQL_SP';

SELECT * FROM SCHEDULE.EMPLOYEES_MULTISQL_SP;


--Using Conditions(WHEN) with TASKS 

CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE =COMPUTE_WH
SCHEDULE ='10 MINUTE'
WHEN 1=2
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_WHEN_1_2 
AS 
SELECT * FROM HR.EMPLOYEES;


ALTER TASK TASK_CREATE_TABLE  RESUME;


EXECUTE TASK TASK_CREATE_TABLE;

SHOW TABLES LIKE 'EMPLOYEES_WHEN_1_2';

SHOW TASKS;


CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE =COMPUTE_WH
SCHEDULE ='10 MINUTE'
WHEN TRUE   --1=1
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES_TRUE 
AS 
SELECT * FROM HR.EMPLOYEES;


ALTER TASK TASK_CREATE_TABLE  RESUME;

EXECUTE TASK TASK_CREATE_TABLE;


SHOW TABLES LIKE 'EMPLOYEES_TRUE';


SELECT * FROM SCHEDULE.EMPLOYEES_TRUE;



SHOW TASKS;



CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE =COMPUTE_WH
SCHEDULE ='10 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('<stream_name>')
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES 
AS 
SELECT * FROM HR.EMPLOYEES;




CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE =COMPUTE_WH
SCHEDULE ='10 MINUTE'
WHEN current_date=to_date('1-MAY-2045')
AS
CREATE OR REPLACE TABLE SCHEDULE.EMPLOYEES 
AS 
SELECT * FROM HR.EMPLOYEES;


--Create a tree/Hierarchy of Tasks/DAG


CREATE OR REPLACE TABLE TASK_ANALYTICS
(
TASK_ID        INTEGER   ,
LVL_ID         VARCHAR(10) , 
TASK_NAME      VARCHAR(256),
UPDATE_DATE    TIMESTAMP
);


CREATE OR REPLACE SEQUENCE SEQ_TASK_ANALYTICS
START WITH 1 , INCREMENT BY 1 ORDER;


CREATE OR REPLACE TASK TASK_ROOT_LVL0
WAREHOUSE =COMPUTE_WH
SCHEDULE ='10 MINUTE'
AS
INSERT INTO TASK_ANALYTICS(TASK_ID, LVL_ID,TASK_NAME,UPDATE_DATE) 
VALUES (SEQ_TASK_ANALYTICS.NEXTVAL,'LVL0','TASK_ROOT_LVL0',CURRENT_TIMESTAMP);

CREATE OR REPLACE TASK C_LVL1_A
WAREHOUSE =COMPUTE_WH
--SCHEDULE ='10 MINUTE'
AFTER TASK_ROOT_LVL0
AS
INSERT INTO TASK_ANALYTICS(TASK_ID, LVL_ID,TASK_NAME,UPDATE_DATE) 
VALUES (SEQ_TASK_ANALYTICS.NEXTVAL,'LVL1','C_LVL1_A',CURRENT_TIMESTAMP);

CREATE OR REPLACE TASK C_LVL1_B
WAREHOUSE =COMPUTE_WH
AFTER TASK_ROOT_LVL0
AS
INSERT INTO TASK_ANALYTICS(TASK_ID, LVL_ID,TASK_NAME,UPDATE_DATE) 
VALUES (SEQ_TASK_ANALYTICS.NEXTVAL,'LVL1','C_LVL1_B',CURRENT_TIMESTAMP);


CREATE OR REPLACE TASK C_LVL1_C
WAREHOUSE =COMPUTE_WH
AFTER TASK_ROOT_LVL0
AS
INSERT INTO TASK_ANALYTICS(TASK_ID, LVL_ID,TASK_NAME,UPDATE_DATE) 
VALUES (SEQ_TASK_ANALYTICS.NEXTVAL,'LVL1','C_LVL1_C',CURRENT_TIMESTAMP);

CREATE OR REPLACE TASK C_LVL1_D
WAREHOUSE =COMPUTE_WH
AFTER TASK_ROOT_LVL0
AS
INSERT INTO TASK_ANALYTICS(TASK_ID, LVL_ID,TASK_NAME,UPDATE_DATE) 
VALUES (SEQ_TASK_ANALYTICS.NEXTVAL,'LVL1','C_LVL1_D',CURRENT_TIMESTAMP);


CREATE OR REPLACE TASK GC_LVL2_E
WAREHOUSE =COMPUTE_WH
AFTER C_LVL1_A
AS
INSERT INTO TASK_ANALYTICS(TASK_ID, LVL_ID,TASK_NAME,UPDATE_DATE) 
VALUES (SEQ_TASK_ANALYTICS.NEXTVAL,'LVL2','GC_LVL2_E',CURRENT_TIMESTAMP);


CREATE OR REPLACE TASK GC_LVL2_F
WAREHOUSE =COMPUTE_WH
AFTER C_LVL1_A
AS
INSERT INTO TASK_ANALYTICS(TASK_ID, LVL_ID,TASK_NAME,UPDATE_DATE) 
VALUES (SEQ_TASK_ANALYTICS.NEXTVAL,'LVL2','GC_LVL2_F',CURRENT_TIMESTAMP);

CREATE OR REPLACE TASK GGC_LVL3_G
WAREHOUSE =COMPUTE_WH
AFTER GC_LVL2_E
AS
INSERT INTO TASK_ANALYTICS(TASK_ID, LVL_ID,TASK_NAME,UPDATE_DATE) 
VALUES (SEQ_TASK_ANALYTICS.NEXTVAL,'LVL3','GGC_LVL2_G',CURRENT_TIMESTAMP);


CREATE OR REPLACE TASK GGC_LVL3_H
WAREHOUSE =COMPUTE_WH
AFTER GC_LVL2_E
AS
INSERT INTO TASK_ANALYTICS(TASK_ID, LVL_ID,TASK_NAME,UPDATE_DATE) 
VALUES (SEQ_TASK_ANALYTICS.NEXTVAL,'LVL3','GGC_LVL3_H',CURRENT_TIMESTAMP);


SHOW TASKS LIKE '%LVL%'

ALTER TASK TASK_ROOT_LVL0   RESUME;
ALTER TASK C_LVL1_A    RESUME;
ALTER TASK TASK_ROOT_LVL0   SUSPEND;


ALTER TASK GGC_LVL3_H  RESUME;
ALTER TASK GGC_LVL3_G  RESUME;
ALTER TASK GC_LVL2_E   RESUME;
ALTER TASK GC_LVL2_F   RESUME;
ALTER TASK C_LVL1_A    RESUME;
ALTER TASK C_LVL1_B    RESUME;
ALTER TASK C_LVL1_C    RESUME;
ALTER TASK C_LVL1_D    RESUME;

ALTER TASK TASK_ROOT_LVL0   RESUME;

SHOW TASKS LIKE '%LVL%'

ALTER TASK TASK_ROOT_LVL0   SUSPEND;

SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('TASK_ROOT_LVL0');

ALTER TASK TASK_ROOT_LVL0   RESUME;

EXECUTE TASK TASK_ROOT_LVL0 ;

TRUNCATE TABLE TASK_ANALYTICS

SELECT * FROM TASK_ANALYTICS ORDER BY 1,2 ;


--How to find  dependencies between tasks.

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(TASK_NAME=>'TASK_ROOT_LVL0',RECURSIVE=>FALSE));


SELECT NAME, PREDECESSORS FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
TASK_NAME=>'TASK_ROOT_LVL0',RECURSIVE=>FALSE));

SELECT NAME TASK_NAME, PREDECESSORS PARENT_TASK_NAME FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
TASK_NAME=>'TASK_ROOT_LVL0',RECURSIVE=>FALSE));

SELECT NAME TASK_NAME, PREDECESSORS PARENT_TASK_NAME FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
TASK_NAME=>'C_LVL1_A',RECURSIVE=>FALSE));

SELECT NAME TASK_NAME, PREDECESSORS PARENT_TASK_NAME FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
TASK_NAME=>'GC_LVL2_E',RECURSIVE=>FALSE));

SELECT NAME TASK_NAME, PREDECESSORS PARENT_TASK_NAME FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
TASK_NAME=>'GGC_LVL3_H',RECURSIVE=>FALSE));

--Recursive =True.

SELECT NAME TASK_NAME, PREDECESSORS PARENT_TASK_NAME FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
TASK_NAME=>'TASK_ROOT_LVL0',RECURSIVE=>TRUE));

SELECT NAME TASK_NAME, PREDECESSORS PARENT_TASK_NAME FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
TASK_NAME=>'C_LVL1_A',RECURSIVE=>TRUE));

SELECT NAME TASK_NAME, PREDECESSORS PARENT_TASK_NAME FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
TASK_NAME=>'GC_LVL2_E',RECURSIVE=>TRUE));

SELECT NAME TASK_NAME, PREDECESSORS PARENT_TASK_NAME FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(
TASK_NAME=>'GGC_LVL3_H',RECURSIVE=>TRUE));



--MONITORING TASKS -ACCOUNT_USAGE.

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY
                    (SCHEDULED_TIME_RANGE_START=>DATEADD('HOUR',-24,CURRENT_TIMESTAMP()),
                     SCHEDULED_TIME_RANGE_END =>CURRENT_TIMESTAMP(),    
                     TASK_NAME=>'TASK_ROOT_LVL0',
                     ERROR_ONLY=>FALSE
                    ))

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY
                    (SCHEDULED_TIME_RANGE_START=>DATEADD('HOUR',-24*7,CURRENT_TIMESTAMP()),  
                     TASK_NAME=>'TASK_ROOT_LVL0',
                     ERROR_ONLY=>FALSE
                    ))

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE SCHEMA_NAME='SCHEDULE';


SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY
                    (SCHEDULED_TIME_RANGE_START=>DATEADD('HOUR',-24*7,CURRENT_TIMESTAMP()),  
                     TASK_NAME=>'TASK_ROOT_LVL0',
                     ERROR_ONLY=>TRUE
                    ))



--Using Snowsight to see Task Depenencies


--FINALIZE TASK

CREATE OR REPLACE TABLE TASK_LOG
(
TASK_LOG_ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
TASK_LOG_TEXT STRING,
LAST_INSERTED_TS DATE
);


ALTER TASK TASK_ROOT_LVL0  SUSPEND;


CREATE OR REPLACE TASK TASK_LOG_FINALIZE
WAREHOUSE = COMPUTE_WH
FINALIZE = TASK_ROOT_LVL0
AS
INSERT INTO TASK_LOG(TASK_LOG_TEXT,LAST_INSERTED_TS) 
       VALUES('TASK EXECUTION OF ROOT TASK IS COMPLETE',CURRENT_TIMESTAMP);


ALTER TASK TASK_LOG_FINALIZE  RESUME;

EXECUTE TASK TASK_LOG_FINALIZE;

SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('TASK_ROOT_LVL0');

ALTER TASK TASK_ROOT_LVL0   RESUME;

EXECUTE TASK TASK_ROOT_LVL0;


SELECT * FROM TASK_LOG;


ALTER TASK TASK_LOG_FINALIZE UNSET FINALIZE;

ALTER TASK TASK_ROOT_LVL0  SUSPEND;


ALTER TASK TASK_LOG_FINALIZE SET FINALIZE = 'TASK_ROOT_LVL0';




--Inserting and Updating a table with Tasks and Merge command.                    

CREATE OR REPLACE TABLE EMPLOYEES_DIM_MERGE
(
EMPLOYEE_ID        NUMBER(6,0),
FIRST_NAME         VARCHAR(20),
LAST_NAME          VARCHAR(25),
EMAIL              VARCHAR(25),
PHONE_NUMBER       VARCHAR(20),
HIRE_DATE          DATE,
JOB_ID             VARCHAR(10),
SALARY             NUMBER(8,2),
COMMISSION_PCT     NUMBER(2,2),
MANAGER_ID         NUMBER(6,0),
DEPARTMENT_ID      NUMBER(4,0),
LAST_UPDATED_TS    TIMESTAMP ,
LAST_INSERTED_TS   TIMESTAMP 
);


CREATE OR REPLACE TASK TASK_UPDATE_EMPLOYEES_DIM_MERGE
WAREHOUSE = COMPUTE_WH 
SCHEDULE = '10 MINUTE'
AS
MERGE INTO SCHEDULE.EMPLOYEES_DIM_MERGE EDIM
USING HR.EMPLOYEES E
ON E.EMPLOYEE_ID = EDIM.EMPLOYEE_ID 
WHEN MATCHED THEN UPDATE
        SET 
        EDIM.EMPLOYEE_ID     = E.EMPLOYEE_ID,
        EDIM.FIRST_NAME      = E.FIRST_NAME,
        EDIM.LAST_NAME       = E.LAST_NAME,
        EDIM.EMAIL           = E.EMAIL,  
        EDIM.PHONE_NUMBER    = E.PHONE_NUMBER,
        EDIM.HIRE_DATE       = E.HIRE_DATE,
        EDIM.JOB_ID          = E.JOB_ID,  
        EDIM.SALARY          = E.SALARY,
        EDIM.COMMISSION_PCT  = E.COMMISSION_PCT,
        EDIM.MANAGER_ID      = E.MANAGER_ID, 
        EDIM.DEPARTMENT_ID   = E.DEPARTMENT_ID,
        EDIM.LAST_UPDATED_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT 
(EDIM.EMPLOYEE_ID,EDIM.FIRST_NAME, EDIM.LAST_NAME, EDIM.EMAIL, EDIM.PHONE_NUMBER,      
                                                                    EDIM.HIRE_DATE,EDIM.JOB_ID,EDIM.SALARY,EDIM.COMMISSION_PCT,EDIM.MANAGER_ID,EDIM.DEPARTMENT_ID,EDIM.LAST_UPDATED_TS,EDIM.LAST_INSERTED_TS)
VALUES
(E.EMPLOYEE_ID,E.FIRST_NAME, E.LAST_NAME, E.EMAIL, E.PHONE_NUMBER, E.HIRE_DATE,E.JOB_ID, E.SALARY,E.COMMISSION_PCT,E.MANAGER_ID,E.DEPARTMENT_ID,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


ALTER TASK TASK_UPDATE_EMPLOYEES_DIM_MERGE  RESUME;


EXECUTE TASK TASK_UPDATE_EMPLOYEES_DIM_MERGE;


SELECT * FROM EMPLOYEES_DIM_MERGE;


SELECT COUNT(*),'EMPLOYEES_DIM_MERGE' TABLE_NAME FROM SCHEDULE.EMPLOYEES_DIM_MERGE
UNION ALL
SELECT COUNT(*),'EMPLOYEES' TABLE_NAME  FROM HR.EMPLOYEES;



UPDATE EMPLOYEES_DIM_MERGE
SET SALARY =0;


SELECT * FROM EMPLOYEES_DIM_MERGE;


EXECUTE TASK TASK_UPDATE_EMPLOYEES_DIM_MERGE;

--Inserting data using the Copy command.

CREATE OR REPLACE TABLE EMPLOYEES_COPY
(
EMPLOYEE_ID        NUMBER(6,0),
FIRST_NAME         VARCHAR(20),
LAST_NAME          VARCHAR(25),
EMAIL              VARCHAR(25),
PHONE_NUMBER       VARCHAR(20),
HIRE_DATE          STRING,
JOB_ID             VARCHAR(10),
SALARY             NUMBER(8,2),
COMMISSION_PCT     STRING,
MANAGER_ID         NUMBER(6,0),
DEPARTMENT_ID      NUMBER(4,0)
);

CREATE OR REPLACE TASK TASK_EMPLOYEES_COPY
WAREHOUSE = COMPUTE_WH 
SCHEDULE ='USING CRON 0 4,0 * * 1-5 America/Chicago' 
AS
COPY INTO EMPLOYEES_COPY FROM @HRSTAGE;

ALTER TASK TASK_EMPLOYEES_COPY  RESUME;

EXECUTE TASK TASK_EMPLOYEES_COPY;

SELECT * FROM EMPLOYEES_COPY;


















CREATE STAGE HRSTAGE
URL='s3://learn2cloud-snowflake/loadingdata/'
STORAGE_INTEGRATION = AWS_S3_INT

SELECT  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11 FROM @HRSTAGE;

SHOW TASKS

DESCRIBE TASK C_LVL1_A
  
SELECT system$stream_has_data('<stream_name>');



ALTER TASK TASK_UPDATE_EMPLOYEES_DIM_MERGE  SUSPEND;